<#
.Synopsis
   CREATE EPM USER
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO CREATE A NEW EPM USER AND ASSIGN LEVEL OF ACCESS
.PARAMETER token
   HashTable of data containing various pieces of login information (EPMServer, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASEPMToken
.PARAMETER newPassword
   New password that will be set for the new EPM user
.PARAMETER ConfirmNewPassword
   Confirm new password that will be set for the new EPM user
.PARAMETER SecurityQuestion
   Security question that will be set for the new EPM user
.PARAMETER SecurityAnswer
   Security answer that will be set for the new EPM user
.PARAMETER roleaccess
   Define the level of access that will be given to the new EPM user
   Possible values: unknown, full_control, read_only
.EXAMPLE
   $NewUser = Add-VPASEPMNewUser -NewUsername "NewUser@company.com" -NewPassword {PASSWORD VALUE} -ConfirmNewPassword {PASSWORD VALUE} -SecurityQuestion {SECURITY QUESTION VALUE} -SecurityAnswer {SECURITY ANSWER VALUE} -roleaccess {ROLE ACCESS VALUE}
.OUTPUTS
   $true if successful
   $false if failed
#>
function Add-VPASEPMNewUser{
    [OutputType([bool])]
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter new user username (email format)",Position=0)]
        [String]$NewUsername,

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter new user password",Position=1)]
        [String]$NewPassword,

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Confirm new user password",Position=2)]
        [String]$ConfirmNewPassword,

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter new user security question",Position=3)]
        [String]$SecurityQuestion,

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter new user security answer",Position=4)]
        [String]$SecurityAnswer,

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter new user level of access (unknown, full_control, read_only)",Position=5)]
        [ValidateSet('unknown','full_control','read_only')]
        [String]$roleaccess,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=6)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$ManagerURL,$Header,$EPMServer,$EnableTextRecorder,$AuditTimeStamp,$HideWarnings,$AuthenticatedAs = Get-VPASEPMSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED MANAGING URL VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            $params = @{
                username = $NewUsername
                password = $NewPassword
                confirmpassword = $ConfirmNewPassword
                question = $SecurityQuestion
                answer = $SecurityAnswer
                roleaccess = $roleaccess
            } | ConvertTo-Json
            $OutputParams = @{
                username = $NewUsername
                password = "{NewPassword}"
                confirmpassword = "{NewPassword}"
                question = "{SecurityQuestion}"
                answer = "{SecurityAnswer}"
                roleaccess = $roleaccess
            }
            Write-Verbose "FINISHED SETTING UP API PARAMETERS"
            $log = Write-VPASEPMTextRecorder -inputval $OutputParams -token $token -LogType PARAMS

            $uri = "$ManagerURL/EPM/API/Account/Users"
            Write-Verbose "SETTING URI: $uri"
            
            $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASEPMTextRecorder -inputval "POST" -token $token -LogType METHOD
            write-verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Body $params -Method POST -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Body $params -Method POST -ContentType "application/json"
            }

            $log = Write-VPASEPMTextRecorder -inputval "SUCCESSFULLY CREATED NEW EPM USER: $NewUsername" -token $token -LogType MISC
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: TRUE" -token $token -LogType MISC
            Write-Verbose "SUCCESSFULLY CREATED NEW EPM USER: $NewUsername"
            Write-Verbose "RETURNING TRUE"
            return $true
        }catch{
            $log = Write-VPASEPMTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO CREATE NEW EPM USER"
            Write-VPASEPMOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
