<#
.Synopsis
   GET ALL AGENT CONFIGURATIONS
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET ALL AGENT CONFIGURATIONS FROM EPM
.PARAMETER token
   HashTable of data containing various pieces of login information (EPMServer, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASEPMToken
.PARAMETER SetID
   UniqueID of the target set
.PARAMETER SetName
   Unique name of the target set
.EXAMPLE
   $AllAgentConfigurations = Get-VPASEPMAllAgentConfigurations -SetName {SETNAME VALUE}
.EXAMPLE
   $AllAgentConfigurations = Get-VPASEPMAllAgentConfigurations -SetID {SETID VALUE}
.OUTPUTS
   JSON Object (AllAgentConfigurations) if successful
   $false if failed
#>
function Get-VPASEPMAllAgentConfigurations{
    [OutputType('System.Object',[bool])]
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=0)]
        [String]$SetName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [String]$SetID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$ManagerURL,$Header,$EPMServer,$EnableTextRecorder,$AuditTimeStamp,$HideWarnings,$AuthenticatedAs = Get-VPASEPMSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED MANAGING URL VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            if([String]::IsNullOrEmpty($SetID)){
                Write-Verbose "NO SETID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE SET ID BASED ON SPECIFIED PARAMETERS"
                $SetID = Get-VPASEPMSetIDHelper -token $token -SearchQuery $SetName
                Write-Verbose "RETURNING SET ID"
            }
            else{
                Write-Verbose "SETID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($SetID -eq -1){
                $log = Write-VPASEPMTextRecorder -inputval "COULD NOT FIND TARGET SET ID: $SetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET SETID: $SetID"
                Write-VPASEPMOutput -str "COULD NOT FIND TARGET SETID: $SetID" -type E
                return $false
            }
            else{
                $apiLimit = 1000
                $uri = "$ManagerURL/EPM/API/Sets/$SetID/Policies/AgentConfiguration/Search?limit=$apiLimit"
                Write-Verbose "SETTING URI: $uri"

                $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
                $log = Write-VPASEPMTextRecorder -inputval "POST" -token $token -LogType METHOD
                write-verbose "MAKING API CALL TO CYBERARK"

                if($sessionval){
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method POST -ContentType "application/json" -WebSession $sessionval
                }
                else{
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method POST -ContentType "application/json"
                }

                $curcount = $response.TotalCount
                $curcount = $curcount - $apiLimit
                $curPolicies = $response.Policies
                $curOffset = 0
                while($curcount -gt 0){
                    $curOffset += $apiLimit
                    $uri = "$ManagerURL/EPM/API/Sets/$SetID/Policies/AgentConfigurations/Search?limit=$apiLimit&offset=$curOffset"
                    Write-Verbose "SETTING URI: $uri"

                    $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
                    $log = Write-VPASEPMTextRecorder -inputval "POST" -token $token -LogType METHOD
                    write-verbose "MAKING API CALL TO CYBERARK"

                    if($sessionval){
                        $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method POST -ContentType "application/json" -WebSession $sessionval
                    }
                    else{
                        $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method POST -ContentType "application/json"
                    }
                    $log = Write-VPASEPMTextRecorder -inputval $response -token $token -LogType RETURN

                    $curcount = $curcount - $apiLimit
                    $curPolicies += $response.Policies
                }
                $response.Policies = $curPolicies
                Write-Verbose "RETURNING JSON OBJECT"
                return $response
            }
        }catch{
            $log = Write-VPASEPMTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO RETRIEVE AGENT CONFIGURATIONS FOR SET: $SetID FROM EPM"
            Write-VPASEPMOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
