<#
.Synopsis
   GET ACCOUNT ADMIN AUDIT
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETRIEVE AUDIT RECORDINGS PERFORMED BY ACCOUNT ADMINISTRATORS
.PARAMETER token
   HashTable of data containing various pieces of login information (EPMServer, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASEPMToken
.PARAMETER FromTime
   Optional parameter to specify a target start range to pull audit records from
.PARAMETER ToTime
   Optional parameter to specify a target end range to pull audit records from
.EXAMPLE
   $AuditData = Get-VPASEPMAccountAdminAudit
.EXAMPLE
   $AuditData = Get-VPASEPMAccountAdminAudit -FromTime "6/7/2024" -ToTime "7/7/2024" 
.OUTPUTS
   JSON Object (AuditData) if successful
   $false if failed
#>
function Get-VPASEPMAccountAdminAudit{
    [OutputType('System.Object',[bool])]
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [datetime]$FromTime,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [datetime]$ToTime,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=3)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$ManagerURL,$Header,$EPMServer,$EnableTextRecorder,$AuditTimeStamp,$HideWarnings,$AuthenticatedAs = Get-VPASEPMSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED MANAGING URL VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            $apiLimit = 500
            $uri = "$ManagerURL/EPM/API/Account/AdminAudit?limit=$apiLimit"

            if(![String]::IsNullOrEmpty($FromTime)){
                $uri += "&DateFrom=$FromTime"
            }
            if(![String]::IsNullOrEmpty($ToTime)){
                $uri += "&DateTo=$ToTime"
            }
            Write-Verbose "SETTING URI: $uri"

            $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASEPMTextRecorder -inputval "GET" -token $token -LogType METHOD
            write-verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            
            $curcount = $response.TotalCount
            $curcount = $curcount - $apiLimit
            $curPolicies = $response.AdminAudits
            $curOffset = 0
            while($curcount -gt 0){
                $curOffset += $apiLimit
                $uri = "$ManagerURL/EPM/API/Account/AdminAudit?limit=$apiLimit&offset=$curOffset"
                if(![String]::IsNullOrEmpty($FromTime)){
                    $uri += "&DateFrom=$FromTime"
                }
                if(![String]::IsNullOrEmpty($ToTime)){
                    $uri += "&DateTo=$ToTime"
                }
                Write-Verbose "SETTING URI: $uri"

                $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
                $log = Write-VPASEPMTextRecorder -inputval "GET" -token $token -LogType METHOD
                write-verbose "MAKING API CALL TO CYBERARK"

                if($sessionval){
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
                }
                else{
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
                }
                $log = Write-VPASEPMTextRecorder -inputval $response -token $token -LogType RETURN

                $curcount = $curcount - $apiLimit
                $curPolicies += $response.AdminAudits
            }
            $response.AdminAudits = $curPolicies
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASEPMTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO GET ACCOUNT ADMIN AUDIT"
            Write-VPASEPMOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
