<#
.Synopsis
   GET EPM AGENT CONFIGURATION DETAILS
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETRIEVE DETAILS FOR AN AGENT CONFIGURATION IN EPM
.PARAMETER token
   HashTable of data containing various pieces of login information (EPMServer, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASEPMToken
.PARAMETER SetID
   UniqueID of the target set
.PARAMETER SetName
   Unique name of the target set
.PARAMETER AgentConfigurationID
   UniqueID of the target Agent Configuration
.PARAMETER AgentConfigurationName
   Unique name of the target Agent Configuration
.EXAMPLE
   $AgentConfigurationDetails = Get-VPASEPMAgentConfigurationDetails -SetName {SETNAME VALUE} -AgentConfigurationName {AGENT CONFIGURATION NAME VALUE}
.EXAMPLE
   $AgentConfigurationDetails = Get-VPASEPMAgentConfigurationDetails -SetID {SETID VALUE} -AgentConfigurationName {AGENT CONFIGURATION NAME VALUE}
.EXAMPLE
   $AgentConfigurationDetails = Get-VPASEPMAgentConfigurationDetails -SetName {SETNAME VALUE} -AgentConfigurationID {AGENT CONFIGURATION ID VALUE}
.EXAMPLE
   $AgentConfigurationDetails = Get-VPASEPMAgentConfigurationDetails -SetID {SETID VALUE} -AgentConfigurationID {AGENT CONFIGURATION ID VALUE}
.OUTPUTS
   JSON Object (AgentConfigurationDetails) if successful
   $false if failed
#>
function Get-VPASEPMAgentConfigurationDetails{
    [OutputType('System.Object',[bool])]
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=0)]
        [String]$SetName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [String]$SetID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [String]$AgentConfigurationName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=3)]
        [String]$AgentConfigurationID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=4)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$ManagerURL,$Header,$EPMServer,$EnableTextRecorder,$AuditTimeStamp,$HideWarnings,$AuthenticatedAs = Get-VPASEPMSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED MANAGING URL VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            if([String]::IsNullOrEmpty($SetID)){
                Write-Verbose "NO SETID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE SET ID BASED ON SPECIFIED PARAMETERS"
                $SetID = Get-VPASEPMSetIDHelper -token $token -SearchQuery $SetName
                Write-Verbose "RETURNING SET ID"
            }
            else{
                Write-Verbose "SETID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($SetID -eq -1){
                $log = Write-VPASEPMTextRecorder -inputval "COULD NOT FIND TARGET SET ID: $SetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET SETID: $SetID"
                Write-VPASEPMOutput -str "COULD NOT FIND TARGET SETID: $SetID" -type E
                return $false
            }
            else{
                if([String]::IsNullOrEmpty($AgentConfigurationID)){
                    Write-Verbose "NO AGENT CONFIGURATION ID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE AGENT CONFIGURATION ID BASED ON SPECIFIED PARAMETERS"
                    $AgentConfigurationID = Get-VPASEPMAgentConfigurationIDHelper -token $token -SearchQuery $AgentConfigurationName -SetID $SetID
                    Write-Verbose "RETURNING AGENT CONFIGURATION ID"
                }
                else{
                    Write-Verbose "AGENT CONFIGURATION ID SUPPLIED, SKIPPING HELPER FUNCTION"
                }

                if($AgentConfigurationID -eq -1){
                    $log = Write-VPASEPMTextRecorder -inputval "MULTIPLE AGENT CONFIGURATION ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS" -token $token -LogType MISC
                    $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                    Write-Verbose "MULTIPLE AGENT CONFIGURATION ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS"
                    Write-VPASEPMOutput -str "MULTIPLE AGENT CONFIGURATION ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS" -type E
                    return $false
                }
                elseif($AgentConfigurationID -eq -2){
                    $log = Write-VPASEPMTextRecorder -inputval "NO AGENT CONFIGURATION ENTRIES WERE RETURNED" -token $token -LogType MISC
                    $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                    Write-Verbose "NO AGENT CONFIGURATION ENTRIES WERE RETURNED"
                    Write-VPASEPMOutput -str "NO AGENT CONFIGURATION ENTRIES WERE RETURNED" -type E
                    return $false
                }
                else{
                    $uri = "$ManagerURL/EPM/API/Sets/$SetID/Policies/AgentConfiguration/$AgentConfigurationID"
                    Write-Verbose "SETTING URI: $uri"

                    $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
                    $log = Write-VPASEPMTextRecorder -inputval "GET" -token $token -LogType METHOD
                    write-verbose "MAKING API CALL TO CYBERARK"

                    if($sessionval){
                        $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
                    }
                    else{
                        $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
                    }
                    $log = Write-VPASEPMTextRecorder -inputval $response -token $token -LogType RETURN
                    Write-Verbose "RETURNING JSON OBJECT"
                    return $response
                }
            }
        }catch{
            $log = Write-VPASEPMTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO RETRIEVE AGENT CONFIGURATION DETAILS"
            Write-VPASEPMOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
