<#
.Synopsis
   GET EPM VERSION
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET CURRENT VERSION OF EPM
.PARAMETER token
   HashTable of data containing various pieces of login information (EPMServer, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASEPMToken
.EXAMPLE
   $EPMVersion = Get-VPASEPMVersion
.OUTPUTS
   JSON Object (EPMVersion) if successful
   $false if failed
#>
function Get-VPASEPMVersion{
    [OutputType('System.Object',[bool])]
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=0)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$ManagerURL,$Header,$EPMServer,$EnableTextRecorder,$AuditTimeStamp,$HideWarnings,$AuthenticatedAs = Get-VPASEPMSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED MANAGING URL VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            $uri = "$ManagerURL/EPM/API/Server/Version"
            Write-Verbose "SETTING URI: $uri"
            
            $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASEPMTextRecorder -inputval "GET" -token $token -LogType METHOD
            write-verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $log = Write-VPASEPMTextRecorder -inputval $response -token $token -LogType RETURN
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASEPMTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO GET EPM VERSION"
            Write-VPASEPMOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
