<#
.Synopsis
   MOVE COMPUTERS TO A DIFFERENT SET
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO MOVE A COMPUTER OBJECT FROM ONE SET TO ANOTHER
.PARAMETER token
   HashTable of data containing various pieces of login information (EPMServer, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASEPMToken
.PARAMETER FromSetID
   UniqueID of the target set
.PARAMETER FromSetName
   Unique name of the target set
.PARAMETER ToSetID
   UniqueID of the target set
.PARAMETER ToSetName
   Unique name of the target set
.PARAMETER ComputerID
   UniqueID of the target computer object
.PARAMETER ComputerName
   Unique name of the target computer object
.EXAMPLE
   $MoveComputer = Move-VPASEPMComputerSet -FromSetName {FROM SETNAME VALUE} -ToSetName {TO SETNAME VALUE} -ComputerName {COMPUTER NAME VALUE}
.EXAMPLE
   $MoveComputer = Move-VPASEPMComputerSet -FromSetID {FROM SETID VALUE} -ToSetID {TO SETID VALUE} -ComputerID {COMPUTER ID VALUE}
.OUTPUTS
   $true if successful
   $false if failed
#>
function Move-VPASEPMComputerSet{
    [OutputType([bool])]
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=0)]
        [String]$FromSetName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [String]$FromSetID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [String]$ToSetName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=3)]
        [String]$ToSetID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=4)]
        [String]$ComputerName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=5)]
        [String]$ComputerID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=6)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$ManagerURL,$Header,$EPMServer,$EnableTextRecorder,$AuditTimeStamp,$HideWarnings,$AuthenticatedAs = Get-VPASEPMSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED MANAGING URL VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            #FROM SET
            if([String]::IsNullOrEmpty($FromSetID)){
                Write-Verbose "NO SETID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE SET ID BASED ON SPECIFIED PARAMETERS"
                $FromSetID = Get-VPASEPMSetIDHelper -token $token -SearchQuery $FromSetName
                Write-Verbose "RETURNING SET ID"
            }
            else{
                Write-Verbose "SETID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($FromSetID -eq -1){
                $log = Write-VPASEPMTextRecorder -inputval "COULD NOT FIND TARGET SET ID: $FromSetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET SETID: $FromSetID"
                Write-VPASEPMOutput -str "COULD NOT FIND TARGET SETID: $FromSetID" -type E
                return $false
            }

            #TO SET
            if([String]::IsNullOrEmpty($ToSetID)){
                Write-Verbose "NO SETID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE SET ID BASED ON SPECIFIED PARAMETERS"
                $ToSetID = Get-VPASEPMSetIDHelper -token $token -SearchQuery $ToSetName
                Write-Verbose "RETURNING SET ID"
            }
            else{
                Write-Verbose "SETID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($ToSetID -eq -1){
                $log = Write-VPASEPMTextRecorder -inputval "COULD NOT FIND TARGET SET ID: $ToSetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET SETID: $ToSetID"
                Write-VPASEPMOutput -str "COULD NOT FIND TARGET SETID: $ToSetID" -type E
                return $false
            }

            #COMPUTER ID
            if([String]::IsNullOrEmpty($ComputerID)){
                Write-Verbose "NO COMPUTER ID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE COMPUTER ID BASED ON SPECIFIED PARAMETERS"
                $ComputerID = Get-VPASEPMAgentIDHelper -token $token -SearchQuery $ComputerName -SetID $FromSetID
                Write-Verbose "RETURNING COMPUTER ID"
            }
            else{
                Write-Verbose "COMPUTER ID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($ComputerID -eq -1){
                $log = Write-VPASEPMTextRecorder -inputval "MULTIPLE AGENT ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "MULTIPLE AGENT ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS"
                Write-VPASEPMOutput -str "MULTIPLE AGENT ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS" -type E
                return $false
            }
            elseif($ComputerID -eq -2){
                $log = Write-VPASEPMTextRecorder -inputval "NO AGENTS WERE RETURNED" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "NO AGENTS WERE RETURNED"
                Write-VPASEPMOutput -str "NO AGENTS WERE RETURNED" -type E
                return $false
            }
            else{
                $params = @{
                    computerIds = @($ComputerID)
                    destSetId = $ToSetID
                }
                Write-Verbose "FINISHED SETTING UP API PARAMETERS"
                $log = Write-VPASEPMTextRecorder -inputval $params -token $token -LogType PARAMS
                $params = $params | ConvertTo-Json

                $uri = "$ManagerURL/EPM/API/Sets/$FromSetID/Computers/RedirectAgents"
                Write-Verbose "SETTING URI: $uri"

                $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
                $log = Write-VPASEPMTextRecorder -inputval "POST" -token $token -LogType METHOD
                write-verbose "MAKING API CALL TO CYBERARK"

                if($sessionval){
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Body $params -Method POST -ContentType "application/json" -WebSession $sessionval
                }
                else{
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Body $params -Method POST -ContentType "application/json"
                }

                $log = Write-VPASEPMTextRecorder -inputval "SUCCESSFULLY MOVED $ComputerID FROM $FromSetID TO $ToSetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: TRUE" -token $token -LogType MISC
                Write-Verbose "RETURNING TRUE"
                return $true
            }
        }catch{
            $log = Write-VPASEPMTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO MOVE COMPUTER OBJECT"
            Write-VPASEPMOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
