<#
.Synopsis
   UNBIND USER FROM SET
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO UNBIND A SPECIFIC USER FROM A SET
.PARAMETER token
   HashTable of data containing various pieces of login information (EPMServer, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASEPMToken
.PARAMETER BindUser
   The user that will be unbound from the set
   Value should be entered as an email address (BindUser@company.com)
.PARAMETER Role
   The users role in the set that will be removed
   Possible values: FullControlSetAdmin, ViewOnlySetAdmin
.PARAMETER SetID
   UniqueID of the set that the user will be unbound from
.PARAMETER SetName
   Unique name of the set that the user will be unbound from
.EXAMPLE
   $UnbindUser = Remove-VPASEPMUserFromSet -UnbindUser "NewUser@company.com" -Role {ROLE VALUE} -SetID {SETID VALUE}
.EXAMPLE
   $UnbindUser = Remove-VPASEPMUserFromSet -UnbindUser "NewUser@company.com" -Role {ROLE VALUE} -SetName {SET NAME VALUE}
.OUTPUTS
   $true if successful
   $false if failed
#>
function Remove-VPASEPMUserFromSet{
    [OutputType([bool])]
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter user email address to unbind from set",Position=0)]
        [String]$UnbindUser,

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter user role that will be removed (FullControlSetAdmin, ViewOnlySetAdmin)",Position=1)]
        [ValidateSet('FullControlSetAdmin','ViewOnlySetAdmin')]
        [String]$Role,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [String]$SetName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=3)]
        [String]$SetID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=4)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$ManagerURL,$Header,$EPMServer,$EnableTextRecorder,$AuditTimeStamp,$HideWarnings,$AuthenticatedAs = Get-VPASEPMSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED MANAGING URL VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            if([String]::IsNullOrEmpty($SetID)){
                Write-Verbose "NO SETID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE SET ID BASED ON SPECIFIED PARAMETERS"
                $SetID = Get-VPASEPMSetIDHelper -token $token -SearchQuery $SetName
                Write-Verbose "RETURNING SET ID"
            }
            else{
                Write-Verbose "SETID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($SetID -eq -1){
                $log = Write-VPASEPMTextRecorder -inputval "COULD NOT FIND TARGET SET ID: $SetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET SETID: $SetID"
                Write-VPASEPMOutput -str "COULD NOT FIND TARGET SETID: $SetID" -type E
                return $false
            }
            else{
                $setParams = @{
                    role = $Role
                    setId = $SetID
                    bind = $false
                }
                $userParams = @{
                    username = $unbindUser
                    Sets = @($setParams)
                }
                $params = @{
                    UserToSets = @($userParams)
                }
                Write-Verbose "FINISHED SETTING UP API PARAMETERS"
                $log = Write-VPASEPMTextRecorder -inputval $params -token $token -LogType PARAMS
                $params = $params | ConvertTo-Json -Depth 5

                $uri = "$ManagerURL/EPM/API/Account/Users/Bind"
                Write-Verbose "SETTING URI: $uri"

                $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
                $log = Write-VPASEPMTextRecorder -inputval "POST" -token $token -LogType METHOD
                write-verbose "MAKING API CALL TO EPM"

                if($sessionval){
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Body $params -Method POST -ContentType "application/json" -WebSession $sessionval
                }
                else{
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Body $params -Method POST -ContentType "application/json"
                }

                $log = Write-VPASEPMTextRecorder -inputval "SUCCESSFULLY UNBOUND USER: $UnbindUser FROM SETID: $SetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: TRUE" -token $token -LogType MISC
                Write-Verbose "SUCCESSFULLY UNBOUND USER: $BindUser FROM SETID: $SetID"
                Write-Verbose "RETURNING TRUE"
                return $true
            }
        }catch{
            $log = Write-VPASEPMTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO UNBIND USER: $BindUser FROM SETID: $SetID"
            Write-VPASEPMOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
