<#
.Synopsis
   REMOVE COMPUTER
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO REMOVE A COMPUTER OBJECT FROM A SET
.PARAMETER token
   HashTable of data containing various pieces of login information (EPMServer, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASEPMToken
.PARAMETER SetID
   UniqueID of the target set
.PARAMETER SetName
   Unique name of the target set
.PARAMETER ComputerID
   UniqueID of the target computer object
.PARAMETER ComputerName
   Unique name of the target computer object
.EXAMPLE
   $RemoveComputer = Remove-VPASEPMComputer -SetName {SETNAME VALUE} -ComputerName {COMPUTER NAME VALUE}
.EXAMPLE
   $RemoveComputer = Remove-VPASEPMComputer -SetID {SETID VALUE} -ComputerID {COMPUTER ID VALUE}
.OUTPUTS
   $true if successful
   $false if failed
#>
function Remove-VPASEPMComputer{
    [OutputType([bool])]
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=0)]
        [String]$SetName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [String]$SetID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [String]$ComputerName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=3)]
        [String]$ComputerID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=4)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$ManagerURL,$Header,$EPMServer,$EnableTextRecorder,$AuditTimeStamp,$HideWarnings,$AuthenticatedAs = Get-VPASEPMSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED MANAGING URL VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            #FROM SET
            if([String]::IsNullOrEmpty($SetID)){
                Write-Verbose "NO SETID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE SET ID BASED ON SPECIFIED PARAMETERS"
                $SetID = Get-VPASEPMSetIDHelper -token $token -SearchQuery $SetName
                Write-Verbose "RETURNING SET ID"
            }
            else{
                Write-Verbose "SETID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($SetID -eq -1){
                $log = Write-VPASEPMTextRecorder -inputval "COULD NOT FIND TARGET SET ID: $SetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET SETID: $SetID"
                Write-VPASEPMOutput -str "COULD NOT FIND TARGET SETID: $SetID" -type E
                return $false
            }

            #COMPUTER ID
            if([String]::IsNullOrEmpty($ComputerID)){
                Write-Verbose "NO COMPUTER ID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE COMPUTER ID BASED ON SPECIFIED PARAMETERS"
                $ComputerID = Get-VPASEPMAgentIDHelper -token $token -SearchQuery $ComputerName -SetID $SetID
                Write-Verbose "RETURNING COMPUTER ID"
            }
            else{
                Write-Verbose "COMPUTER ID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($ComputerID -eq -1){
                $log = Write-VPASEPMTextRecorder -inputval "MULTIPLE AGENT ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "MULTIPLE AGENT ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS"
                Write-VPASEPMOutput -str "MULTIPLE AGENT ENTRIES WERE RETURNED, ADD MORE TO SEARCH TO NARROW RESULTS" -type E
                return $false
            }
            elseif($ComputerID -eq -2){
                $log = Write-VPASEPMTextRecorder -inputval "NO AGENTS WERE RETURNED" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "NO AGENTS WERE RETURNED"
                Write-VPASEPMOutput -str "NO AGENTS WERE RETURNED" -type E
                return $false
            }
            else{
                $uri = "$ManagerURL/EPM/API/Sets/$SetID/Computers/$ComputerID"
                Write-Verbose "SETTING URI: $uri"

                $log = Write-VPASEPMTextRecorder -inputval $uri -token $token -LogType URI
                $log = Write-VPASEPMTextRecorder -inputval "DELETE" -token $token -LogType METHOD
                write-verbose "MAKING API CALL TO CYBERARK"

                if($sessionval){
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method DELETE -ContentType "application/json" -WebSession $sessionval
                }
                else{
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method DELETE -ContentType "application/json"
                }

                $log = Write-VPASEPMTextRecorder -inputval "SUCCESSFULLY REMOVED $ComputerID FROM $SetID" -token $token -LogType MISC
                $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: TRUE" -token $token -LogType MISC
                Write-Verbose "RETURNING TRUE"
                return $true
            }
        }catch{
            $log = Write-VPASEPMTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASEPMTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO REMOVE COMPUTER OBJECT"
            Write-VPASEPMOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASEPMTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
