<#
.Synopsis
   GET ALL CONNECTOR MANAGEMENT CONNECTOR COMPONENTS
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETRIEVE CONNECTOR COMPONENTS FROM CONNECTOR MANAGEMENT
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER ConnectorID
   UniqueID of the target connector in ConnectorManagement
.PARAMETER ConnectorHost
   Unique host of the target connector in ConnectorManagement
   Host in this case can either be a hostname, a publicIP, or a PrivateIP
.EXAMPLE
   $ConnectorComponents = Get-VPASCMAllConnectorComponents -ConnectorID {CONNECTOR ID VALUE}
.EXAMPLE
   $ConnectorComponents = Get-VPASCMAllConnectorComponents -ConnectorHost {CONNECTOR NAME VALUE}
.OUTPUTS
   JSON Object (ConnectorComponents) if successful
   $false if failed
#>
function Get-VPASCMAllConnectorComponents{
    [OutputType('System.Collections.Hashtable',[bool])]
    [CmdletBinding()]
    Param(

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=0)]
        [String]$ConnectorID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [String]$ConnectorHost,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED SUBDOMAIN VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            if($SubDomain -eq "N/A"){
                Write-VPASOutput -str "SelfHosted + PriviledgeCloud Standard solutions do not support this API Call, returning false" -type E
                $log = Write-VPASTextRecorder -inputval "SelfHosted + PrivilegeCloud Standard solutions do not support this API Call, returning false" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval $false -token $token -LogType RETURN
                return $false
            }

            if([String]::IsNullOrEmpty($ConnectorID)){
                Write-Verbose "NO CONNECTOR ID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE CONNECTOR ID BASED ON SPECIFIED PARAMETERS"
                $ConnectorID = Get-VPASCMConnectorIDHelper -token $token -SearchQuery $ConnectorHost
                Write-Verbose "RETURNING CONNECTOR ID"
            }
            else{
                Write-Verbose "CONNECTOR ID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($ConnectorID -eq -1){
                $log = Write-VPASTextRecorder -inputval "COULD NOT FIND TARGET CONNECTOR ID: $ConnectorID" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET CONNECTOR ID: $ConnectorID"
                Write-VPASOutput -str "COULD NOT FIND TARGET CONNECTOR ID: $ConnectorID" -type E
                return $false
            }
            else{
                write-verbose "MAKING API CALL TO CYBERARK"
                $uri = "https://$SubDomain.connectormanagement.cyberark.cloud/api/connectors/$ConnectorID/components"
                Write-Verbose "CONSTRUCTING URI: $uri"

                $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
                $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

                if($sessionval){
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
                }
                else{
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
                }
                $log = Write-VPASTextRecorder -inputval $response -token $token -LogType RETURNARRAY
                Write-Verbose "RETURNING CONNECTOR COMPONENT DETAILS"
                return $response
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE CONNECTOR MANAGEMENT CONNECTOR COMPONENTS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
