<#
.Synopsis
   GET CYBERARK SYSTEM COMPONENTS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET SYSTEMHEALTH INFORMATION FROM CYBERARK
.LINK
   https://vpasmodule.com/commands/Get-VPASSystemComponents
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.EXAMPLE
   $SystemComponentsJSON = Get-VPASSystemComponents
.EXAMPLE
   $InputParameters = @{}
   $SystemComponentsJSON = Get-VPASSystemComponents -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "Components":  [
                           {
                               "ComponentID":  "PVWA",
                               "ComponentName":  "PVWA",
                               "Description":  "Active Users",
                               "ConnectedComponentCount":  1,
                               "ComponentTotalCount":  2,
                               "ComponentSpecificStat":  1
                           },
                           {
                               "ComponentID":  "CPM",
                               "ComponentName":  "CPM",
                               "Description":  "Managed Accounts",
                               "ConnectedComponentCount":  0,
                               "ComponentTotalCount":  5,
                               "ComponentSpecificStat":  24
                           },
                           {
                               "ComponentID":  "SessionManagement",
                               "ComponentName":  "PSM/PSMP",
                               "Description":  "Concurrent Sessions",
                               "ConnectedComponentCount":  0,
                               "ComponentTotalCount":  7,
                               "ComponentSpecificStat":  0
                           },
                           {
                               "ComponentID":  "AIM",
                               "ComponentName":  "AAM Credential Provider",
                               "Description":  "Applications",
                               "ConnectedComponentCount":  0,
                               "ComponentTotalCount":  2,
                               "ComponentSpecificStat":  5
                           }
                       ],
        "Vaults":  [
                       {
                           "IP":  "vault-vman.pcloudprod.cyberarkinternal.com",
                           "Role":  "Primary",
                           "IsLoggedOn":  true
                       }
                   ]
   }
   ---
   $false if failed
#>
function Get-VPASSystemComponents{
    [OutputType('System.Object',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(
        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @()
                        MandatoryKeys = @()
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE SYSTEM COMPONENTS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{

            Write-Verbose "MAKING API CALL TO CYBERARK"
            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/PasswordVault/api/ComponentsMonitoringSummary"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/PasswordVault/api/ComponentsMonitoringSummary"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $outputlog = $response | ConvertTo-Json | ConvertFrom-Json
            $log = Write-VPASTextRecorder -inputval $outputlog -token $token -LogType RETURNARRAY
            Write-Verbose "PARSING DATA FROM CYBERARK"
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO RETRIEVE SYSTEM COMPONENT INFORMATION FROM CYBERARK"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}


