<#
.Synopsis
   GET ALL CONNECTOR MANAGEMENT CONNECTORS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETRIEVE ALL CONNECTORS FROM CONNECTOR MANAGEMENT
.LINK
   https://vpasmodule.com/commands/Get-VPASCMAllConnectors
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.EXAMPLE
   $AllConnectors = Get-VPASCMAllConnectors
.EXAMPLE
   $InputParameters = @{}
   $AllConnectors = Get-VPASCMAllConnectors -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "connectors":  [
                           {
                               "connectorId":  "ManagementAgent_28jhfkjshfjk-24523-876575-fgbcgb-kjh0909",
                               "connectorStatus":  "Disconnected",
                               "platformType":  "OnPrem",
                               "connectorPoolId":  "hdaskljhfkwsd8-2344-65434-asdfsa-askjdh87493",
                               "version":  "1.0.581.0",
                               "upgradeVersions":  "",
                               "installedAt":  1723673190630,
                               "updatedAt":  1724093199151,
                               "host":  "@{hostname=VpasConn1; privateIp=192.168.111.111; publicIp=10.20.22.333; os=windows; osVersion=10.0.17763; osName=Windows Server 2019 Datacenter Evaluation; cloudRegion=; cloudAccount=; cpuType=AMD Ryzen 7 PRO 7840U w/ Radeon 780MGraphics  ; totalCpu=2; usedCpu=-1.0; totalMemory=7.999046325683594; usedMemory=-1.0; hostConfig=}",
                               "components":  "   "
                           },
                           {
                               "connectorId":  "ManagementAgent_jkhj687273-1111-dddd-sd34534-msndkl983745",
                               "connectorStatus":  "Active",
                               "platformType":  "OnPrem",
                               "connectorPoolId":  "askjdhasjkd-321342-asdad-asdas-89213kjsdbakjaq",
                               "version":  "1.0.483.0",
                               "upgradeVersions":  "v1.0.581",
                               "installedAt":  1712952182564,
                               "updatedAt":  1719436401060,
                               "host":  "@{hostname=VpasCon2; privateIp=192.168.222.222; publicIp=10.20.44.555; os=windows; osVersion=10.0.20348; osName=Windows Server 2022 Standard; cloudRegion=; cloudAccount=; cpuType=13th Gen Intel(R) Core(TM) i7-1360P; totalCpu=1; usedCpu=0.2; totalMemory=3.999034881591797; usedMemory=43.0; hostConfig=}",
                               "components":  "   "
                           }
                       ]
   }
   ---
   $false if failed
#>
function Get-VPASCMAllConnectors{
    [OutputType('System.Collections.Hashtable',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(
        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @()
                        MandatoryKeys = @()
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE CONNECTORS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{
            if($SubDomain -eq "N/A"){
                Write-VPASOutput -str "SelfHosted + PriviledgeCloud Standard solutions do not support this API Call, returning false" -type E
                $log = Write-VPASTextRecorder -inputval "SelfHosted + PrivilegeCloud Standard solutions do not support this API Call, returning false" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval $false -token $token -LogType RETURN
                return $false
            }

            write-verbose "MAKING API CALL TO CYBERARK"
            $uri = "https://$SubDomain.connectormanagement.cyberark.cloud/api/connectors"
            Write-Verbose "CONSTRUCTING URI: $uri"

            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $log = Write-VPASTextRecorder -inputval $response -token $token -LogType RETURNARRAY
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE CONNECTOR MANAGEMENT CONNECTORS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
