<#
.Synopsis
   COMPLETE CYBERARK QUERY
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO SEARCH FOR A TARGET VALUE IN ALL ASSETS LIKE SAFES, ACCOUNTS, PLATFORMS, MEMBERS, ETC.
.LINK
   https://vpasmodule.com/commands/Find-VPASTargetValue
.NOTES
   SelfHosted: TRUE
   PrivCloudStandard: TRUE
   SharedServices: TRUE
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER SearchQuery
   Search string to find target resource via username, address, safe, platform, etc.
.PARAMETER SkipSafes
   Flag to ignore safes, getting safe data will be skipped
.PARAMETER SkipAccounts
   Flag to ignore accounts, getting account data will be skipped
.PARAMETER SkipPlatforms
   Flag to ignore platforms, getting platform data will be skipped
.PARAMETER SkipEPVUsers
   Flag to ignore EPVUsers, getting EPVUser data will be skipped
.PARAMETER SkipEPVGroups
   Flag to ignore EPVGroups, getting EPVGroup data will be skipped
.PARAMETER SkipApplications
   Flag to ignore applications, getting applicationID data will be skipped
.PARAMETER SkipRoles
   Flag to ignore roles, getting role data will be skipped
.PARAMETER SkipIdentities
   Flag to ignore identities, getting identity data will be skipped
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.PARAMETER ExportToCSV
   Output results to a CSV file found in AppData\Local\VPASModuleOutputs directory
.PARAMETER CSVDirectory
   Output directory where the exported CSV file will be saved to
   Default value: C:\Users\{CurrentUser}\AppData\Local\VPASModuleOutputs\ExportedCSVs
.EXAMPLE
   $Output = Find-VPASTargetValue -searchQuery {SEARCHQUERY VALUE}
.EXAMPLE
   $InputParameters = @{
        searchQuery = $true|$false
        SkipSafes = $true|$false
        SkipAccounts = $true|$false
        SkipPlatforms = $true|$false
        SkipEPVUsers = $true|$false
        SkipEPVGroups = $true|$false
        SkipApplications = $true|$false
        SkipRoles = $true|$false
        SkipIdentities = $true|$false
        ExportToCSV = $true|$false
        CSVDirectory = "C:\Temp"
   }
   $Output = Find-VPASTargetValue -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
    ...
        (
            ExtraInfo   @{safeNumber=124; location=\; creator=; olacEnabled=False; numberOfVersionsRetention=; numberOfDaysRetention=7;...
            Condition   vadim matched on safe creator: vadim@vman.com
            Asset       Safe
            Value       testsafe001
        ),
    ...
   }
   ---
   $false if failed
#>
function Find-VPASTargetValue{
    [OutputType('System.Object','System.Collections.Hashtable',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(
        [Parameter(Mandatory=$true,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true,HelpMessage="Enter wildcard search to query for Safes (for example: Win_)")]
        [String]$searchQuery,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$SkipSafes,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$SkipAccounts,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$SkipPlatforms,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$SkipEPVUsers,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$SkipEPVGroups,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$SkipApplications,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$SkipRoles,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$SkipIdentities,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$ExportToCSV,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [String]$CSVDirectory,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("searchQuery","SkipSafes","SkipAccounts","SkipPlatforms","SkipEPVUsers","SkipEPVGroups","SkipApplications","SkipRoles","SkipIdentities","ExportToCSV","CSVDirectory")
                        MandatoryKeys = @("searchQuery")
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE TARGET VALUES"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{
            $outputmatrix = @()

            #SAFES
            if($SkipSafes){
                Write-VPASOutput -str "Step1) Pulling all safes and safe members...SKIPPING" -type M
            }
            else{
                Write-VPASOutput -str "Step1) Pulling all safes and safe members" -type DY
                write-verbose "PULLING ALL SAFES..."
                $AllSafes = Get-VPASAllSafes
                foreach($safe in $AllSafes.value){
                    $safename = $safe.safeName
                    $safecreator = $safe.creator.name
                    $safedescription = $safe.description

                    if($safename -match $searchQuery){
                        $outhash = @{
                            Asset = "Safe"
                            Value = $safename
                            Condition = "$searchQuery matched on safe name: $safename"
                            ExtraInfo = $safe
                        }
                        $outputmatrix += $outhash
                    }
                    if($safedescription -match $searchQuery){
                        $outhash = @{
                            Asset = "Safe"
                            Value = $safename
                            Condition = "$searchQuery matched on safe description: $safedescription"
                            ExtraInfo = $safe
                        }
                        $outputmatrix += $outhash
                    }
                    if($safecreator -match $searchQuery){
                        $outhash = @{
                            Asset = "Safe"
                            Value = $safename
                            Condition = "$searchQuery matched on safe creator: $safecreator"
                            ExtraInfo = $safe
                        }
                        $outputmatrix += $outhash
                    }

                    #SAFE MEMBERS
                    $AllSafeMembers = Get-VPASSafeMembers -safe $safename -IncludePredefinedMembers
                    foreach($mem in $AllSafeMembers.value){
                        $targetmember = $mem.memberName
                        if($targetmember -match $searchQuery){
                            $outhash = @{
                                Asset = "SafeMember"
                                Value = $safename
                                Condition = "$searchQuery matched on safe member: $targetmember on safe: $safename"
                                ExtraInfo = $safe
                            }
                            $outputmatrix += $outhash
                        }
                    }
                }
            }

            #ACCOUNTS
            if($SkipAccounts){
                Write-VPASOutput -str "Step2) Pulling all account objects and properties...SKIPPING" -type M
            }
            else{
                Write-VPASOutput -str "Step2) Pulling all account objects and properties" -type DY
                write-verbose "PULLING ALL ACCOUNTS..."
                $AllAccounts = Get-VPASAllAccounts
                foreach($acct in $AllAccounts.value){
                    $acctname = $acct.name
                    $acctaddress = $acct.address
                    $acctusername = $acct.userName
                    $acctAllProps = $acct.platformAccountProperties.psobject.Properties.name

                    if($acctname -match $searchQuery){
                        $outhash = @{
                            Asset = "Account"
                            Value = $acctname
                            Condition = "$searchQuery matched on account name: $acctname"
                            ExtraInfo = $acct
                        }
                        $outputmatrix += $outhash
                    }
                    if($acctaddress -match $searchQuery){
                        $outhash = @{
                            Asset = "Account"
                            Value = $acctname
                            Condition = "$searchQuery matched on account address: $acctaddress"
                            ExtraInfo = $acct
                        }
                        $outputmatrix += $outhash
                    }
                    if($acctusername -match $searchQuery){
                        $outhash = @{
                            Asset = "Account"
                            Value = $acctname
                            Condition = "$searchQuery matched on account username: $acctusername"
                            ExtraInfo = $acct
                        }
                        $outputmatrix += $outhash
                    }
                    foreach($prop in $acctAllProps){
                        if($prop -ne "Length"){
                            $propval = $acct.platformAccountProperties.$prop

                            if($propval -match $searchQuery){
                                $outhash = @{
                                    Asset = "Account"
                                    Value = $acctname
                                    Condition = "$searchQuery matched on account property: $prop"
                                    ExtraInfo = $acct
                                }
                                $outputmatrix += $outhash
                            }
                        }
                    }
                }
            }

            #PLATFORMS
            if($SkipPlatforms){
                Write-VPASOutput -str "Step3) Pulling all platform details...SKIPPING" -type M
            }
            else{
                Write-VPASOutput -str "Step3) Pulling all platform details" -type DY
                write-verbose "PULLING ALL PLATFORMS..."
                $AllPlatforms = Get-VPASAllPlatforms
                foreach($plat in $AllPlatforms.Platforms){
                    $platID = $plat.general.id
                    $platName = $plat.general.name
                    $platDescription = $plat.general.description
                    $platRequired = @()
                    $platOptional = @()

                    foreach($prop in $plat.properties.required){
                        $platRequired += $prop.name
                        $platRequired += $prop.displayName
                    }
                    foreach($prop in $plat.properties.optional){
                        $platOptional += $prop.name
                        $platOptional += $prop.displayName
                    }

                    $AllowedSafes = $plat.credentialsManagement.allowedSafes

                    if($platID -match $searchQuery){
                        $outhash = @{
                            Asset = "Platform"
                            Value = $platID
                            Condition = "$searchQuery matched on Platform ID: $platID"
                            ExtraInfo = $plat
                        }
                        $outputmatrix += $outhash
                    }
                    if($platName -match $searchQuery){
                        $outhash = @{
                            Asset = "Platform"
                            Value = $platID
                            Condition = "$searchQuery matched on Platform Name: $platName"
                            ExtraInfo = $plat
                        }
                        $outputmatrix += $outhash
                    }
                    if($platDescription -match $searchQuery){
                        $outhash = @{
                            Asset = "Platform"
                            Value = $platID
                            Condition = "$searchQuery matched on Platform Description: $platDescription"
                            ExtraInfo = $plat
                        }
                        $outputmatrix += $outhash
                    }
                    if($AllowedSafes -match $searchQuery){
                        $outhash = @{
                            Asset = "Platform"
                            Value = $platID
                            Condition = "$searchQuery matched on Platform Allowed Safes: $AllowedSafes"
                            ExtraInfo = $plat
                        }
                        $outputmatrix += $outhash
                    }
                    foreach($prop in $platRequired){
                        if($prop -match $searchQuery){
                            $outhash = @{
                                Asset = "Platform"
                                Value = $platID
                                Condition = "$searchQuery matched on Platform Required Property: $prop"
                                ExtraInfo = $plat
                            }
                            $outputmatrix += $outhash
                        }
                    }
                    foreach($prop in $platOptional){
                        if($prop -match $searchQuery){
                            $outhash = @{
                                Asset = "Platform"
                                Value = $platID
                                Condition = "$searchQuery matched on Platform Optional Property: $prop"
                                ExtraInfo = $plat
                            }
                            $outputmatrix += $outhash
                        }
                    }
                }
            }

            #EPVUSERS
            if($SkipEPVUsers){
                Write-VPASOutput -str "Step4) Pulling all epv users...SKIPPING" -type M
            }
            else{
                Write-VPASOutput -str "Step4) Pulling all epv users" -type DY
                write-verbose "PULLING ALL EPVUSERS..."
                $AllEPVUsers = Get-VPASAllEPVUsers
                foreach($epvuser in $AllEPVUsers.Users){
                    $epvusername = $epvuser.username
                    $epvfirstname = $epvuser.personalDetails.firstName
                    $epvlastname = $epvuser.personalDetails.lastName

                    if($epvusername -match $searchQuery){
                        $outhash = @{
                            Asset = "EPVUser"
                            Value = $epvusername
                            Condition = "$searchQuery matched on EPV Username: $epvusername"
                            ExtraInfo = $epvuser
                        }
                        $outputmatrix += $outhash
                    }
                    if($epvfirstname -match $searchQuery){
                        $outhash = @{
                            Asset = "EPVUser"
                            Value = $epvusername
                            Condition = "$searchQuery matched on EPV Firstname: $epvfirstname"
                            ExtraInfo = $epvuser
                        }
                        $outputmatrix += $outhash
                    }
                    if($epvlastname -match $searchQuery){
                        $outhash = @{
                            Asset = "EPVUser"
                            Value = $epvusername
                            Condition = "$searchQuery matched on EPV Lastname: $epvlastname"
                            ExtraInfo = $epvuser
                        }
                        $outputmatrix += $outhash
                    }
                }
            }

            #EPV GROUPS
            if($SkipEPVGroups){
                Write-VPASOutput -str "Step5) Pulling all epv groups...SKIPPING" -type M
            }
            else{
                Write-VPASOutput -str "Step5) Pulling all epv groups" -type DY
                write-verbose "PULLING ALL EPVGROUPS..."
                $AllEPVGroups = Get-VPASAllEPVGroups
                foreach($epvgroup in $AllEPVGroups.value){
                    $epvgroupname = $epvgroup.groupName
                    $epvgroupdescription = $epvgroup.description

                    if($epvgroupname -match $searchQuery){
                        $outhash = @{
                            Asset = "EPVGroup"
                            Value = $epvgroupname
                            Condition = "$searchQuery matched on EPV Group Name: $epvgroupname"
                            ExtraInfo = $epvgroup
                        }
                        $outputmatrix += $outhash
                    }
                    if($epvgroupdescription -match $searchQuery){
                        $outhash = @{
                            Asset = "EPVGroup"
                            Value = $epvgroupname
                            Condition = "$searchQuery matched on EPV Group Description: $epvgroupdescription"
                            ExtraInfo = $epvgroup
                        }
                        $outputmatrix += $outhash
                    }
                }
            }

            #APPLICATION IDS
            if($SkipApplications){
                Write-VPASOutput -str "Step6) Pulling all applicationIDs and application authentication methods...SKIPPING" -type M
            }
            else{
                Write-VPASOutput -str "Step6) Pulling all applicationIDs and application authentication methods" -type DY
                write-verbose "PULLING ALL APPLICATIONS..."
                $AllApplications = Get-VPASAllApplications
                foreach($app in $AllApplications){
                    $appAppID = $app.AppID
                    $appBusinessOwnerEmail = $app.BusinessOwnerEmail
                    $appBusinessOwnerFName = $app.BusinessOwnerFName
                    $appBusinessOwnerLName = $app.BusinessOwnerLName
                    $appDescription = $app.Description


                    if($appAppID -match $searchQuery){
                        $outhash = @{
                            Asset = "ApplicationID"
                            Value = $appAppID
                            Condition = "$searchQuery matched on Application ID: $appAppID"
                            ExtraInfo = $app
                        }
                        $outputmatrix += $outhash
                    }
                    if($appBusinessOwnerEmail -match $searchQuery){
                        $outhash = @{
                            Asset = "ApplicationID"
                            Value = $appAppID
                            Condition = "$searchQuery matched on Application Email: $appBusinessOwnerEmail"
                            ExtraInfo = $app
                        }
                        $outputmatrix += $outhash
                    }
                    if($appBusinessOwnerFName -match $searchQuery){
                        $outhash = @{
                            Asset = "ApplicationID"
                            Value = $appAppID
                            Condition = "$searchQuery matched on Application Firstname: $appBusinessOwnerFName"
                            ExtraInfo = $app
                        }
                        $outputmatrix += $outhash
                    }
                    if($appBusinessOwnerLName -match $searchQuery){
                        $outhash = @{
                            Asset = "ApplicationID"
                            Value = $appAppID
                            Condition = "$searchQuery matched on Application Lastname: $appBusinessOwnerLName"
                            ExtraInfo = $app
                        }
                        $outputmatrix += $outhash
                    }
                    if($appDescription -match $searchQuery){
                        $outhash = @{
                            Asset = "ApplicationID"
                            Value = $appAppID
                            Condition = "$searchQuery matched on Application Description: $appDescription"
                            ExtraInfo = $app
                        }
                        $outputmatrix += $outhash
                    }

                    $AllApplicationAuths = Get-VPASApplicationAuthentications -AppID $appAppID
                    foreach($auth in $AllApplicationAuths.authentication){
                        $AuthValue = $auth.AuthValue
                        $Comment = $auth.Comment

                        if($AuthValue -match $searchQuery){
                            $outhash = @{
                                Asset = "ApplicationIDAuth"
                                Value = $appAppID
                                Condition = "$searchQuery matched on Application Authentication Value: $AuthValue"
                                ExtraInfo = $app
                            }
                            $outputmatrix += $outhash
                        }
                        if($Comment -match $searchQuery){
                            $outhash = @{
                                Asset = "ApplicationIDAuth"
                                Value = $appAppID
                                Condition = "$searchQuery matched on Application Authentication Comment: $Comment"
                                ExtraInfo = $app
                            }
                            $outputmatrix += $outhash
                        }
                    }
                }
            }

            #ROLES (IF ISPSS)
            if($ISPSS){
                if($SkipRoles){
                    Write-VPASOutput -str "Step7) Pulling all roles from Identity...SKIPPING" -type M
                }
                else{
                    Write-VPASOutput -str "Step7) Pulling all roles from Identity" -type DY
                    Write-Verbose "PULLING ALL ROLES"
                    $AllRoles = Get-VPASIdentityAllRoles
                    foreach($role in $AllRoles.Value){
                        $roleID = $role.ID
                        $roleName = $role.Name
                        $roleDescription = $role.Description

                        if($roleID -match $searchQuery){
                            $outhash = @{
                                Asset = "Role"
                                Value = $roleName
                                Condition = "$searchQuery matched on Role ID: $roleID"
                                ExtraInfo = $role
                            }
                            $outputmatrix += $outhash
                        }
                        if($roleName -match $searchQuery){
                            $outhash = @{
                                Asset = "Role"
                                Value = $roleName
                                Condition = "$searchQuery matched on Role Name: $roleName"
                                ExtraInfo = $role
                            }
                            $outputmatrix += $outhash
                        }
                        if($roleDescription -match $searchQuery){
                            $outhash = @{
                                Asset = "Role"
                                Value = $roleName
                                Condition = "$searchQuery matched on Role Description: $roleDescription"
                                ExtraInfo = $role
                            }
                            $outputmatrix += $outhash
                        }
                    }
                }

                if($SkipIdentities){
                    Write-VPASOutput -str "Step8) Pulling all Identity objects from Identity...SKIPPING" -type M
                }
                else{
                    Write-VPASOutput -str "Step8) Pulling all Identity objects from Identity" -type DY
                    Write-Verbose "PULLING ALL IDENTITIES"
                    $AllUsers = Get-VPASIdentityAllUsers
                    foreach($user in $AllUsers.Results.row){
                        $userDisplay = $user.DisplayName
                        $userName = $user.Name
                        $userMail = $user.Mail
                        $userDescription = $user.Description

                        if($userDisplay -match $searchQuery){
                            $outhash = @{
                                Asset = "Identity"
                                Value = $userName
                                Condition = "$searchQuery matched on Identity DisplayName: $userDisplay"
                                ExtraInfo = $user
                            }
                            $outputmatrix += $outhash
                        }
                        if($userName -match $searchQuery){
                            $outhash = @{
                                Asset = "Identity"
                                Value = $userName
                                Condition = "$searchQuery matched on Identity Name: $userName"
                                ExtraInfo = $user
                            }
                            $outputmatrix += $outhash
                        }
                        if($userMail -match $searchQuery){
                            $outhash = @{
                                Asset = "Identity"
                                Value = $userName
                                Condition = "$searchQuery matched on Identity Email: $userMail"
                                ExtraInfo = $user
                            }
                            $outputmatrix += $outhash
                        }
                        if($userDescription -match $searchQuery){
                            $outhash = @{
                                Asset = "Identity"
                                Value = $userName
                                Condition = "$searchQuery matched on Identity Description: $userDescription"
                                ExtraInfo = $user
                            }
                            $outputmatrix += $outhash
                        }
                    }
                }
            }

            if($ExportToCSV){
	            $runexport = Write-VPASExportCSV -Data $outputmatrix -CommandName $CommandName -CSVDirectory $CSVDirectory
            }
            return $outputmatrix
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE SAFES"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
