<#
.Synopsis
   GET PSM SESSION DETAILS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET PSM SESSION DETAILS
.LINK
   https://vpasmodule.com/commands/Get-VPASPSMSessionDetails
.NOTES
   SelfHosted: TRUE
   PrivCloudStandard: TRUE
   SharedServices: TRUE
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER SearchQuery
   Search string to find target resource via username, address, safe, platform, etc.
   Comma separated for multiple fields, or to search all pass a blank value like so: " "
.PARAMETER PSMSessionID
   Unique ID that maps to the target PSMSession
   Supply the PSMSessionID to skip any querying to find the target PSMSession
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.PARAMETER ExportToCSV
   Output results to a CSV file found in AppData\Local\VPASModuleOutputs directory
.PARAMETER CSVDirectory
   Output directory where the exported CSV file will be saved to
   Default value: C:\Users\{CurrentUser}\AppData\Local\VPASModuleOutputs\ExportedCSVs
.EXAMPLE
   $GetPSMSessionDetailsJSON = Get-VPASPSMSessionDetails -SearchQuery {SEARCHQUERY VALUE}
.EXAMPLE
   $GetPSMSessionDetailsJSON = Get-VPASPSMSessionDetails -PSMSessionID {PSM SESSION ID VALUE}
.EXAMPLE
   $InputParameters = @{
        SearchQuery = "DomainAdmin01"
        ExportToCSV = $true|$false
        CSVDirectory = "C:\Temp"
   }
   $GetPSMSessionDetailsJSON = Get-VPASPSMSessionDetails -InputParameters $InputParameters
.EXAMPLE
   $InputParameters = @{
        PSMSessionID = "36_101"
        ExportToCSV = $true|$false
        CSVDirectory = "C:\Temp"
   }
   $GetPSMSessionDetailsJSON = Get-VPASPSMSessionDetails -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "Recordings":  [
                           {
                               "SessionID":  "36_102",
                               "SessionGuid":  "kjsad8972-jhgs-lkjw-8976-ksjdhfkj462",
                               "SafeName":  "PSMRecordings",
                               "FolderName":  "Root",
                               "IsLive":  false,
                               "FileName":  "kjsad8972-jhgs-lkjw-8976-ksjdhfkj462.session",
                               "Start":  1712111269,
                               "End":  1712111328,
                               "Duration":  59,
                               "User":  "vadim@vman.com",
                               "RemoteMachine":  "192.168.111.111",
                               "ProtectionDate":  0,
                               "ProtectedBy":  "",
                               "ProtectionEnabled":  false,
                               "AccountUsername":  "vmanda",
                               "AccountPlatformID":  "VadimWindowsDomain",
                               "AccountAddress":  "vman.com",
                               "PIMSuCommand":  "",
                               "PIMSuCWD":  "",
                               "ConnectionComponentID":  "PSM-RDP",
                               "PSMRecordingEntity":  "SessionRecording",
                               "TicketID":  "",
                               "FromIP":  "192.168.222.222",
                               "Protocol":  "RDP",
                               "Client":  "RDP",
                               "RiskScore":  -1,
                               "Severity":  "",
                               "IncidentDetails":  null,
                               "RawProperties":  "@{Address=vman.com; ConnectionComponentID=PSM-RDP; DeviceType=Operating System; EntityVersion=1.0; ExpectedRecordingsList=kjsad8972-jhgs-lkjw-8976-ksjdhfkj462.WIN.txt,kjsad8972-jhgs-lkjw-8976-ksjdhfkj462.VID.avi; PSMClientApp=mstsc.exe; PSMPasswordID=9; PSMProtocol=RDP; PSMRecordingEntity=SessionRecording; PSMRemoteMachine=192.168.111.111; PSMSafeID=68; PSMSourceAddress=192.168.222.222; PSMStartTime=1712111269; PSMStatus=Final; PSMVaultUserName=vadim@vman.com; PolicyID=VadimWindowsDomain; ProviderID=PSMApp_VmanCon01; UserName=vmanda; PSMEndTime=1712111328; ActualRecordings=kjsad8972-jhgs-lkjw-8976-ksjdhfkj462.WIN.txt;187,kjsad8972-jhgs-lkjw-8976-ksjdhfkj462.VID.avi;188; Safe=PSMRecordings; Folder=Root; Name=kjsad8972-jhgs-lkjw-8976-ksjdhfkj462.session}",
                               "RecordingFiles":  " ",
                               "RecordedActivities":  "",
                               "VideoSize":  1772412,
                               "TextSize":  3048,
                               "DetailsUrl":  "recordingdetails.aspx?Data=lkjhf897346958734hr89u734nf05hf0753hf093njf089j4098fjn04398jf09834jf098j34098j309fj8fj3pf093h"
                           }
                       ],
        "Total":  0
   }
   ---
   $false if failed
#>
function Get-VPASPSMSessionDetails{
    [OutputType('System.Object',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(

        [Parameter(Mandatory=$true,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true,HelpMessage="Searchquery to find the target PSM session (for example: DomainAdmin01)")]
        [String]$SearchQuery,

        [Parameter(Mandatory=$true,ParameterSetName='Set2',ValueFromPipelineByPropertyName=$true,HelpMessage="Unique PSMSessionID of the target PSM session (for example: 36_102)")]
        [String]$PSMSessionID,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Parameter(Mandatory=$false,ParameterSetName='Set2',ValueFromPipelineByPropertyName=$true)]
        [Switch]$ExportToCSV,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Parameter(Mandatory=$false,ParameterSetName='Set2',ValueFromPipelineByPropertyName=$true)]
        [String]$CSVDirectory,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("SearchQuery","ExportToCSV","CSVDirectory")
                        MandatoryKeys = @("SearchQuery")
                    }
					set2 = @{
                        AcceptableKeys = @("PSMSessionID","ExportToCSV","CSVDirectory")
                        MandatoryKeys = @("PSMSessionID")
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE PSM SESSIONS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{

            if([String]::IsNullOrEmpty($PSMSessionID)){
                Write-Verbose "NO PSM SESSION ID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE PSM SESSION ID BASED ON SPECIFIED PARAMETERS"
                $PSMSessionID = Get-VPASRecordingIDHelper -token $token -SearchQuery $SearchQuery
                Write-Verbose "RETURNING PSM SESSION ID"
            }
            else{
                Write-Verbose "PSM SESSION ID SUPPLIED, SKIPPING HELPER FUNCTION"
            }


            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/PasswordVault/API/recordings/$PSMSessionID"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/PasswordVault/API/recordings/$PSMSessionID"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

            write-verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            if($ExportToCSV){
	            $runexport = Write-VPASExportCSV -Data $response -CommandName $CommandName -CSVDirectory $CSVDirectory
            }
            $log = Write-VPASTextRecorder -inputval $response -token $token -LogType RETURNARRAY
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO GET PSM SESSION DETAILS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
