<#
.Synopsis
   GET ALL CONNECTOR MANAGEMENT CONNECTOR COMPONENTS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETRIEVE CONNECTOR COMPONENTS FROM CONNECTOR MANAGEMENT
.LINK
   https://vpasmodule.com/commands/Get-VPASCMAllConnectorComponents
.NOTES
   SelfHosted: FALSE
   PrivCloudStandard: FALSE
   SharedServices: TRUE
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER ConnectorID
   UniqueID of the target connector in ConnectorManagement
.PARAMETER ConnectorHost
   Unique host of the target connector in ConnectorManagement
   Host in this case can either be a hostname, a publicIP, or a PrivateIP
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.PARAMETER ExportToCSV
   Output results to a CSV file found in AppData\Local\VPASModuleOutputs directory
.PARAMETER CSVDirectory
   Output directory where the exported CSV file will be saved to
   Default value: C:\Users\{CurrentUser}\AppData\Local\VPASModuleOutputs\ExportedCSVs
.EXAMPLE
   $ConnectorComponents = Get-VPASCMAllConnectorComponents -ConnectorID {CONNECTOR ID VALUE}
.EXAMPLE
   $ConnectorComponents = Get-VPASCMAllConnectorComponents -ConnectorHost {CONNECTOR NAME VALUE}
.EXAMPLE
   $InputParameters = @{
        ConnectorID = "hdjka678-dhakjas789-abcd-9876-kajshd9a00"
        ExportToCSV = $true|$false
        CSVDirectory = "C:\Temp"
   }
   $ConnectorComponents = Get-VPASCMAllConnectorComponents -InputParameters $InputParameters
.EXAMPLE
   $InputParameters = @{
        ConnectorHost = "VmanCon01"
        ExportToCSV = $true|$false
        CSVDirectory = "C:\Temp"
   }
   $ConnectorComponents = Get-VPASCMAllConnectorComponents -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "components":  [
                           {
                               "componentId":  "hdjka678-dhakjas789-7389218-shkja-kajshdjka39246783",
                               "componentName":  "Privileged Session Manager",
                               "acronym":  "psm",
                               "componentStatus":  "Active",
                               "connectorId":  "ManagementAgent_hdjka678-dhakjas789-abcd-9876-kajshd9a00",
                               "version":  "14.2.0.3",
                               "upgradeVersions":  "v14.3.0.8",
                               "usedCpu":  0.304,
                               "usedMemory":  0.949,
                               "installedAt":  1711987268166,
                               "updatedAt":  1723831555919,
                               "maintenanceStatus":  null
                           },
                           {
                               "componentId":  "ManagementAgent_hdjka678-dhakjas789-abcd-9876-kajshd9a00",
                               "componentName":  "Management Agent",
                               "acronym":  "Management Agent",
                               "componentStatus":  "Active",
                               "connectorId":  "ManagementAgent_hdjka678-dhakjas789-abcd-9876-kajshd9a00",
                               "version":  "1.0.483.0",
                               "upgradeVersions":  "v1.0.581",
                               "usedCpu":  2.91,
                               "usedMemory":  0.669,
                               "installedAt":  1710820946924,
                               "updatedAt":  1723831555919,
                               "maintenanceStatus":  null
                           },
                           {
                               "componentId":  "hdjka678-dhakjas789-7389218-shkja-kajshdjka39246783",
                               "componentName":  "Password Manager",
                               "acronym":  "cpm",
                               "componentStatus":  "Active",
                               "connectorId":  "ManagementAgent_hdjka678-dhakjas789-abcd-9876-kajshd9a00",
                               "version":  "14.0.0.6",
                               "upgradeVersions":  "v14.2.1.6",
                               "usedCpu":  0.661,
                               "usedMemory":  0.917,
                               "installedAt":  1710821627249,
                               "updatedAt":  1723831555919,
                               "maintenanceStatus":  null
                           },
                           {
                               "componentId":  "hdjka678-dhakjas789-7389218-shkja-kajshdjka39246783",
                               "componentName":  "Central Policy Manager Scanner",
                               "acronym":  "cpm scanner",
                               "componentStatus":  "Active",
                               "connectorId":  "ManagementAgent_hdjka678-dhakjas789-abcd-9876-kajshd9a00",
                               "version":  "13.2.0.2",
                               "upgradeVersions":  "",
                               "usedCpu":  0.439,
                               "usedMemory":  1.531,
                               "installedAt":  1710821628343,
                               "updatedAt":  1723831555919,
                               "maintenanceStatus":  null
                           }
                       ]
   }
   ---
   $false if failed
#>
function Get-VPASCMAllConnectorComponents{
    [OutputType('System.Collections.Hashtable',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(

        [Parameter(Mandatory=$true,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true,HelpMessage="Unique ConnectorID of the target connector (for example: hsfkjdhf687234-kjhf-sdfj-9876-872364iedhkjwqed)")]
        [String]$ConnectorID,

        [Parameter(Mandatory=$true,ParameterSetName='Set2',ValueFromPipelineByPropertyName=$true,HelpMessage="Name of the host holding the target connector (for example: VmanCon01)")]
        [String]$ConnectorHost,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Parameter(Mandatory=$false,ParameterSetName='Set2',ValueFromPipelineByPropertyName=$true)]
        [Switch]$ExportToCSV,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Parameter(Mandatory=$false,ParameterSetName='Set2',ValueFromPipelineByPropertyName=$true)]
        [String]$CSVDirectory,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("ConnectorID","ExportToCSV","CSVDirectory")
                        MandatoryKeys = @("ConnectorID")
                    }
					set2 = @{
                        AcceptableKeys = @("ConnectorHost","ExportToCSV","CSVDirectory")
                        MandatoryKeys = @("ConnectorHost")
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE CONNECTOR COMPONENTS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{
            if($SubDomain -eq "N/A"){
                Write-VPASOutput -str "SelfHosted + PriviledgeCloud Standard solutions do not support this API Call, returning false" -type E
                $log = Write-VPASTextRecorder -inputval "SelfHosted + PrivilegeCloud Standard solutions do not support this API Call, returning false" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval $false -token $token -LogType RETURN
                return $false
            }

            if([String]::IsNullOrEmpty($ConnectorID)){
                Write-Verbose "NO CONNECTOR ID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE CONNECTOR ID BASED ON SPECIFIED PARAMETERS"
                $ConnectorID = Get-VPASCMConnectorIDHelper -token $token -SearchQuery $ConnectorHost
                Write-Verbose "RETURNING CONNECTOR ID"
            }
            else{
                Write-Verbose "CONNECTOR ID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($ConnectorID -eq -1){
                $log = Write-VPASTextRecorder -inputval "COULD NOT FIND TARGET CONNECTOR ID: $ConnectorID" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET CONNECTOR ID: $ConnectorID"
                Write-VPASOutput -str "COULD NOT FIND TARGET CONNECTOR ID: $ConnectorID" -type E
                return $false
            }
            else{
                write-verbose "MAKING API CALL TO CYBERARK"
                $uri = "https://$SubDomain.connectormanagement.cyberark.cloud/api/connectors/$ConnectorID/components"
                Write-Verbose "CONSTRUCTING URI: $uri"

                $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
                $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

                if($sessionval){
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
                }
                else{
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
                }
                if($ExportToCSV){
	                $runexport = Write-VPASExportCSV -Data $response -CommandName $CommandName -CSVDirectory $CSVDirectory
                }
                $log = Write-VPASTextRecorder -inputval $response -token $token -LogType RETURNARRAY
                Write-Verbose "RETURNING CONNECTOR COMPONENT DETAILS"
                return $response
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE CONNECTOR MANAGEMENT CONNECTOR COMPONENTS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
