<#
.Synopsis
   GET EMPTY PLATFORMS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET ALL THE EMPTY PLATFORMS IN THE ENVIRONMENT
.LINK
   https://vpasmodule.com/commands/Get-VPASEmptyPlatforms
.NOTES
   SelfHosted: TRUE
   PrivCloudStandard: TRUE
   SharedServices: TRUE
.NOTES
   SelfHosted: TRUE
   PrivCloudStandard: TRUE
   SharedServices: TRUE
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.PARAMETER ExportToCSV
   Output results to a CSV file found in AppData\Local\VPASModuleOutputs directory
.PARAMETER CSVDirectory
   Output directory where the exported CSV file will be saved to
   Default value: C:\Users\{CurrentUser}\AppData\Local\VPASModuleOutputs\ExportedCSVs
.EXAMPLE
   $EmptyPlatforms = Get-VPASEmptyPlatforms
.EXAMPLE
   $InputParameters = @{
        ExportToCSV = $true|$false
        CSVDirectory = "C:\Temp"
   }
   $EmptyPlatforms = Get-VPASEmptyPlatforms -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "value":  [
				      ...
                      {
                          "PolicyID":  "BusinessWebsite",
                          "PolicyName":  "Business Website",
                          "SearchForUsages":  "Yes",
                          "PolicyType":  "Regular",
                          "ImmediateInterval":  "5",
                          "Interval":  "1440",
                          "MaxConcurrentConnections":  "3",
                          "AllowedSafes":  "BZ_I_*",
                          "MinValidityPeriod":  "60",
                          "ResetOveridesMinValidity":  "Yes",
                          "ResetOveridesTimeFrame":  "Yes",
                          "Timeout":  "30",
                          "UnlockIfFail":  "No",
                          "UnrecoverableErrors":  "2103,2105,2121",
                          "MaximumRetries":  "5",
                          "MinDelayBetweenRetries":  "90",
                          "ExeName":  "CyberArk.TPC.exe",
                          "DllName":  "",
                          "XMLFile":  "Yes",
                          "AllowManualChange":  "Yes",
                          "PerformPeriodicChange":  "No",
                          "HeadStartInterval":  "5",
                          "FromHour":  "-1",
                          "ToHour":  "-1",
                          "ChangeNotificationPeriod":  "-1",
                          "DaysNotifyPriorExpiration":  "7",
                          "NFNotifyPriorExpiration":  "No",
                          "NFPriorExpirationRecipients":  "",
                          "NFNotifyOnPasswordDisable":  "Yes",
                          "NFOnPasswordDisableRecipients":  "",
                          "NFNotifyOnVerificationErrors":  "Yes",
                          "NFOnVerificationErrorsRecipients":  "",
                          "NFNotifyOnPasswordUsed":  "No",
                          "NFOnPasswordUsedRecipients":  "",
                          "PasswordLength":  "12",
                          "MinUpperCase":  "0",
                          "MinLowerCase":  "0",
                          "MinDigit":  "0",
                          "MinSpecial":  "0",
                          "PasswordForbiddenChars":  "",
                          "EnforcePasswordPolicyOnManualChange":  "No",
                          "EnforcePasswordVersionsHistory":  "-1",
                          "OneTimePassword":  "No",
                          "ExpirationPeriod":  "90",
                          "VFVerificationPeriod":  "7",
                          "PasswordLevelRequestTimeframe":  "No"
                      },
				      ...
                  ]
   }
   ---
   $false if failed
#>
function Get-VPASEmptyPlatforms{
    [OutputType('System.Object',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(
        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$ExportToCSV,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [String]$CSVDirectory,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("ExportToCSV","CSVDirectory")
                        MandatoryKeys = @()
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE PLATFORMS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{
            $outputmatrix = @{
                value = @()
            }
            $platformIDs = @()
            write-verbose "MAKING API CALL TO CYBERARK"

            $AllPlatforms1 = Get-VPASAllPlatforms
            foreach($plat in $AllPlatforms1.Platforms.general.id){
                $platformIDs += $plat
            }

            $AllPlatforms2 = Get-VPASAllTargetPlatforms
            foreach($plat in $AllPlatforms2.Platforms.platformid){
                if(!$platformIDs.Contains($plat)){
                    $platformIDs += $plat
                }
            }

            foreach($plat in $platformIDs){
                if($plat -match "PSMSecureConnect"){
                    #DO NOTHING, INTERNAL PLATFORM
                }
                else{
                    $AllAccounts = Get-VPASAccountDetails -platform $plat -ExactMatch -HideWarning
                    if(!$AllAccounts){
                        $PlatformDetails = Get-VPASPlatformDetails -platformID $plat
                        $outputmatrix.value += $PlatformDetails.Details
                    }
                }
            }
            Write-Verbose "PARSING DATA FROM CYBERARK"
            Write-Verbose "RETURNING PLATFORM DETAILS"
            if($ExportToCSV){
	            $runexport = Write-VPASExportCSV -Data $outputmatrix -CommandName $CommandName -CSVDirectory $CSVDirectory
            }
            return $outputmatrix
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "COULD NOT RETRIEVE PLATFORMS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
