<#
.Synopsis
   GET ALL EPV USERS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET ALL EPV USERS
.LINK
   https://vpasmodule.com/commands/Get-VPASAllEPVUsers
.NOTES
   SelfHosted: TRUE
   PrivCloudStandard: TRUE
   SharedServices: TRUE
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.PARAMETER ExportToCSV
   Output results to a CSV file found in AppData\Local\VPASModuleOutputs directory
.PARAMETER CSVDirectory
   Output directory where the exported CSV file will be saved to
   Default value: C:\Users\{CurrentUser}\AppData\Local\VPASModuleOutputs\ExportedCSVs
.EXAMPLE
   $AllEPVUsersJSON = Get-VPASAllEPVUsers
.EXAMPLE
   $InputParameters = @{
        ExportToCSV = $true|$false
        CSVDirectory = "C:\Temp"
   }
   $AllEPVUsersJSON = Get-VPASAllEPVUsers -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "Users":  [
                      ...
                      {
                          "id":  131,
                          "username":  "VpasLogTest",
                          "source":  "CyberArk",
                          "userType":  "EPVUser",
                          "componentUser":  false,
                          "groupsMembership":  "",
                          "vaultAuthorization":  "",
                          "location":  "\\",
                          "personalDetails":  "@{firstName=; middleName=; lastName=; organization=; department=}",
                          "enableUser":  true,
                          "suspended":  false
                      },
                      {
                          "id":  133,
                          "username":  "regularuser@vman.com",
                          "source":  "CyberArk",
                          "userType":  "EPVUser",
                          "componentUser":  false,
                          "groupsMembership":  "   ",
                          "vaultAuthorization":  "",
                          "location":  "\\",
                          "personalDetails":  "@{firstName=RegularUser; middleName=; lastName=; organization=; department=}",
                          "enableUser":  true,
                          "suspended":  false
                      },
                      {
                          "id":  222,
                          "username":  "normaluser@vpam.com",
                          "source":  "CyberArk",
                          "userType":  "EPVUser",
                          "componentUser":  false,
                          "groupsMembership":  "     ",
                          "vaultAuthorization":  "",
                          "location":  "\\",
                          "personalDetails":  "@{firstName=normaluser; middleName=; lastName=; organization=; department=}",
                          "enableUser":  true,
                          "suspended":  false
                      },
                      ...
                  ],
        "Total":  53
   }
   ---
   $false if failed
#>
function Get-VPASAllEPVUsers{
    [OutputType('System.Object',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(
        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$ExportToCSV,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [String]$CSVDirectory,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("ExportToCSV","CSVDirectory")
                        MandatoryKeys = @()
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE EPV USERS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{

            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/PasswordVault/API/Users?ExtendedDetails=True"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/PasswordVault/api/Users?ExtendedDetails=True"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

            Write-Verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $outputlog = $response
            $log = Write-VPASTextRecorder -inputval $outputlog -token $token -LogType RETURNARRAY
            if($ExportToCSV){
	            $runexport = Write-VPASExportCSV -Data $response -CommandName $CommandName -CSVDirectory $CSVDirectory
            }
            Write-Verbose "SUCCESSFULLY RETRIEVED ALL EPVUSERS"
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO RETRIEVE ALL EPVUSERS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
