<#
.Synopsis
   RUN VARIOUS METRICS FROM CYBERARK
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GENERATE VARIOUS METRICS FROM CYBERARK
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER TargetMetric
   Specify which report will be run
   Possible values: SafeContent, SafeMembers, PlatformDetails, EPVUsers
.PARAMETER HideOutput
   Suppress any output from the console
.EXAMPLE
   $VReporting = Invoke-VPASReporting -ReportType {REPORTTYPE VALUE} -ReportFormat {REPORTFORMAT VALUE} -SearchQuery {SEARCHQUERY VALUE} -OutputDirectory {OUTPUTDIRECTORY VALUE}
.OUTPUTS
   $true if successful
   $false if failed
#>
function Invoke-VPASMetrics{
    [OutputType([bool])]
    [CmdletBinding()]
    Param(

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter TargetMetric to be generated (PSMSessionsInXDays,PSMUtilizationForXDays)",Position=0)]
        [ValidateSet('PSMSessionsInXDays','PSMUtilizationForXDays')]
        [String]$TargetMetric,

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter ReportOutput type (CSV, JSON, TXT, HTML, XML, ALL)",Position=1)]
        [ValidateSet('JSON','HTML','ALL')]
        [String]$MetricFormat,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [String]$OutputDirectory,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=3)]
        [String]$DayRange,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=4)]
        [String]$AmtOfSets,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=5)]
        [ValidateSet('BarGraph','LineGraph','PieChart','ALL')]
        [String]$HTMLChart,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=6)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{

        Write-Verbose "SUCCESSFULLY PARSED PVWA VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TARGET METRIC VALUE: $TargetMetric"
        Write-Verbose "SUCCESSFULLY PARSED METRIC OUTPUT VALUE: $MetricFormat"

        try{
            if([String]::IsNullOrEmpty($OutputDirectory)){
                $curUser = $env:UserName
                $OutputDirectory = "C:\Users\$curUser\AppData\Local\VPASModuleOutputs\Metrics"
                Write-Verbose "NO OUTPUT DIRECTORY SUPPLIED, USING DEFAULT LOCATION: $OutputDirectory"

                if(Test-Path -Path $OutputDirectory){
                    #DO NOTHING
                }
                else{
                    write-verbose "$OutputDirectory DOES NOT EXIST, CREATING DIRECTORY"
                    $MakeDirectory = New-Item -Path $OutputDirectory -Type Directory
                }
            }
            else{
                if(Test-Path -Path $OutputDirectory){
                    #DO NOTHING
                }
                else{
                    $curUser = $env:UserName
                    $OutputDirectory = "C:\Users\$curUser\AppData\Local\VPASModuleOutputs\Metrics"
                    write-verbose "$OutputDirectory DOES NOT EXIST, USING DEFAULT LOCATION: $OutputDirectory"
                    if(Test-Path -Path $OutputDirectory){
                        #DO NOTHING
                    }
                    else{
                        $MakeDirectory = New-Item -Path $OutputDirectory -Type Directory
                    }
                }
            }

            if([String]::IsNullOrEmpty($HTMLChart)){
                $HTMLChart = "BarGraph"
            }

            if($TargetMetric -eq "PSMSessionsInXDays"){
                if([String]::IsNullOrEmpty($DayRange)){
                    Write-VPASOutput -str "NO DayRange SUPPLIED, ENTER DayRange (1 - 365): " -type Y
                    $DayRange = Read-Host
                }
                if([String]::IsNullOrEmpty($AmtOfSets)){
                    Write-VPASOutput -str "NO AmtOfSets SUPPLIED, ENTER AmtOfSets (1 - 365): " -type Y
                    $AmtOfSets = Read-Host
                }
                
                try{
                    $AmtDaysInt = [Int]$DayRange
                    if($AmtDaysInt -lt 1 -or $AmtDaysInt -gt 365){
                        Write-Verbose "INVALID INPUT FOR DAY RANGE: $DayRange ...MUST BE AN INTEGRET BETWEEN 1 - 365"
                        Write-VPASOutput -str "INVALID INPUT FOR DAY RANGE: $DayRange ...MUST BE AN INTEGRET BETWEEN 1 - 365" -type E
                        return $false
                    }
                }catch{
                    Write-Verbose "INVALID INPUT FOR DAY RANGE: $DayRange ...MUST BE AN INTEGER BETWEEN 1 - 365"
                    Write-VPASOutput -str "INVALID INPUT FOR DAY RANGE: $DayRange ...MUST BE AN INTEGER BETWEEN 1 - 365" -type E
                    Write-VPASOutput -str $_ -type E
                    return $false
                }

                try{
                    $AmtSetsInt = [Int]$AmtOfSets
                    if($AmtSetsInt -lt 1 -or $AmtSetsInt -gt 365){
                        Write-Verbose "INVALID INPUT FOR SET AMOUNT: $AmtOfSets...MUST AN INTEGER BETWEEN 1 - 365"
                        Write-VPASOutput -str "INVALID INPUT FOR SET AMOUNT: $AmtOfSets...MUST AN INTEGER BETWEEN 1 - 365" -type E
                        return $false
                    }
                }catch{
                    Write-Verbose "INVALID INPUT FOR SET AMOUNT: $AmtOfSets ...MUST AN INTEGER BETWEEN 1 - 365"
                    Write-VPASOutput -str "INVALID INPUT FOR SET AMOUNT: $AmtOfSets ...MUST AN INTEGER BETWEEN 1 - 365" -type E
                    Write-VPASOutput -str $_ -type E
                    return $false
                }

                


                #INITIALIZE DATE HASH
                $RecordingsHash = @{}
                $CurTime = ([int][double]::Parse((Get-Date (get-date (get-date).Date).ToLocalTime() -UFormat %s))) + 86400
                $NumSeconds = ($AmtDaysInt * 86400)

                $counter = 0
                while($counter -lt $AmtSetsInt){
                    $counter += 1
                    $MaxNum = $CurTime - 1
                    $CurTime = $CurTime - $NumSeconds
                    $MinNum = $CurTime
                    #$CurTime -= 1
                    
                    $UniqueKey = "Set" + $counter
                    $RecordingsHash += @{
                        $UniqueKey = @{
                            Max = $MaxNum
                            Min = $MinNum
                            Count = 0
                            RawData = @()
                        }
                    }
                }

                #GET RECORDINGS
                $AllRecordings = Get-VPASPSMSessions -SearchQuery " "
                if(!$AllRecordings){
                    Write-Verbose "FAILED TO RETRIEVE PSM SESSIONS"
                    Write-VPASOutput -str "FAILED TO RETRIEVE PSM SESSIONS" -type E
                    Write-VPASOutput -str $_ -type E
                    return $false
                }

                foreach($rec in $AllRecordings.Recordings){
                    $EpochStart = $rec.Start

                    $parser = $AmtSetsInt
                    while($parser -gt 0){
                        $uniqueKey = "Set$parser"
                        $setmin = $RecordingsHash.$uniqueKey.Min
                        $setmax = $RecordingsHash.$uniqueKey.Max
                        $setcount = $RecordingsHash.$uniqueKey.Count

                        if($EpochStart -ge $setmin -and $EpochStart -le $setmax){
                            $setcount += 1
                            $RecordingsHash.$uniqueKey.Count = $setcount
                            $parser = 0
                            $RecordingsHash.$UniqueKey.RawData += $rec
                        }
                        else{
                            $parser -= 1
                        }
                    }
                }

                #CONVERT THINGS TO HUMAN READABLE TIME
                $origin = New-Object -Type DateTime -ArgumentList 1970, 1, 1, 0, 0, 0, 0
                $parser = $AmtSetsInt
                while($parser -gt 0){
                    $uniqueKey = "Set$parser"
                    $setmin = $RecordingsHash.$uniqueKey.Min
                    $setmax = $RecordingsHash.$uniqueKey.Max
                    
                    $newmin = $origin.AddSeconds($setmin).ToShortDateString()
                    $newmax = $origin.AddSeconds($setmax).ToShortDateString()

                    $RecordingsHash.$uniqueKey.Min = $newmin
                    $RecordingsHash.$uniqueKey.Max = $newmax

                    $parser -= 1
                }

                if($MetricFormat -eq "JSON" -or $MetricFormat -eq "ALL"){
                    $outputfile = "$OutputDirectory/PSMSessionsIn" + $AmtDaysInt + "Days.json"
                    $OutputDataJSON = $RecordingsHash | ConvertTo-Json
                    Write-Output $OutputDataJSON | Set-Content $outputfile
                    return $OutputDataJSON
                }

                if($MetricFormat -eq "HTML" -or $MetricFormat -eq "ALL"){
                    $outputfile = "$OutputDirectory/PSMSessionsIn" + $AmtDaysInt + "Days.html"
write-output "
<!DOCTYPE html>
<html>
<script src=`"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js`"></script>
<body>
" | Set-content $outputfile
                    
                    if($HTMLChart -eq "BarGraph" -or $HTMLChart -eq "ALL"){
                        write-output "<canvas id=`"myChartBAR`" style=`"width:100%;`"></canvas>`n<br><br><br>`n" | Add-Content $outputfile
                    }
                    if($HTMLChart -eq "LineGraph" -or $HTMLChart -eq "ALL"){
                        write-output "<canvas id=`"myChartLINE`" style=`"width:100%;`"></canvas>`n<br><br><br>`n"| Add-Content $outputfile
                    }
                    if($HTMLChart -eq "PieChart" -or $HTMLChart -eq "ALL"){
                        write-output "<canvas id=`"myChartPIE`" style=`"width:100%;`"></canvas>`n<br><br><br>`n"| Add-Content $outputfile
                    }
                    write-output "<script>" | Add-Content $outputfile

                    $tempstr = ""
                    $tempstr2 = ""
                    $tempstr3 = ""
                    $tempstr4 = ""
                    $AllKeys = $RecordingsHash.Keys
                    $AmtKeys = $AllKeys.Count
                    $counter = 0
                    $GetMinMax = @()

                    while($counter -lt $AmtKeys){
                        $counter += 1
                        $key = "Set$counter"
                        $minVal = $RecordingsHash.$key.Min
                        $maxVal = $RecordingsHash.$key.Max
                        $curCount = $RecordingsHash.$key.count
                        $GetMinMax += $curCount
                        $textColor =  '#{0:X6}' -f (Get-Random -Maximum 0x1000000)

                        $outputstr = "$maxVal - $minVal"
                        $tempstr += "`"$outputstr`","
                        $tempstr2 += "$curCount,"
                        $tempstr3 += "`"green`","
                        $tempstr4 += "`"$textColor`","
                    }

                    $GetMinMax = $GetMinMax | Sort-Object
                    $mintick = $GetMinMax[0]
                    $maxtick = $GetMinMax[$GetMinMax.Count - 1]

                    $tempstr = $tempstr.Substring(0,$tempstr.Length-1)
                    $tempstr2 = $tempstr2.Substring(0,$tempstr2.Length-1)
                    $tempstr3 = $tempstr3.Substring(0,$tempstr3.Length-1)
                    $tempstr4 = $tempstr4.Substring(0,$tempstr4.Length-1)
                    
                    if($HTMLChart -eq "BarGraph" -or $HTMLChart -eq "ALL"){
                        write-output "const xValuesBAR = [$tempstr];" | Add-Content $outputfile
                        write-output "const yValuesBAR = [$tempstr2];" | Add-Content $outputfile
                        write-output "const barColorsBAR = [$tempstr3];" | Add-Content $outputfile
                    }
                    if($HTMLChart -eq "LineGraph" -or $HTMLChart -eq "ALL"){
                        write-output "const xValuesLINE = [$tempstr];" | Add-Content $outputfile
                        write-output "const yValuesLINE = [$tempstr2];" | Add-Content $outputfile
                    }
                    if($HTMLChart -eq "PieChart" -or $HTMLChart -eq "ALL"){
                        write-output "const xValuesPIE = [$tempstr];" | Add-Content $outputfile
                        write-output "const yValuesPIE = [$tempstr2];" | Add-Content $outputfile
                        write-output "const barColorsPIE = [$tempstr4];" | Add-Content $outputfile
                    }

if($HTMLChart -eq "BarGraph" -or $HTMLChart -eq "ALL"){
#BAR
Write-Output "
new Chart(`"myChartBAR`", {
    type: `"bar`",
    data: {
        labels: xValuesBAR,
        datasets: [{
            backgroundColor: barColorsBAR,
            data: yValuesBAR
        }]
    },
    options: {
        legend: {display: false},
        title: {
            display: true,
            text: `"PSM Sessions Made Per $AmtDaysInt Days`"
        }
    }
});
" | Add-Content $outputfile
}
if($HTMLChart -eq "LineGraph" -or $HTMLChart -eq "ALL"){
#LINE
Write-Output "
new Chart(`"myChartLINE`", {
    type: `"line`",
    data: {
        labels: xValuesLINE,
        datasets: [{
            label: `"PSM Sessions Made Per $AmtDaysInt Days`",
            fill: false,
            lineTension: 0,
            backgroundColor: `"rgba(0,0,255,1.0)`",
            borderColor: `"rgba(0,0,255,0.1)`",
            data: yValuesLINE
        }]
    },
    options: {
        legend: {display: true},
        scales: {
            yAxes: [{ticks: {min: $mintick, max:$maxtick}}],
        }
    }
});
" | Add-Content $outputfile
}
if($HTMLChart -eq "PieChart" -or $HTMLChart -eq "ALL"){
#PIE
write-output "
new Chart(`"myChartPIE`", {
    type: `"pie`",
    data: {
        labels: xValuesPIE,
        datasets: [{
            backgroundColor: barColorsPIE,
            data: yValuesPIE
        }]
    },
    options: {
        title: {
            display: true,
            text: `"PSM Sessions Made Per $AmtDaysInt Days`"
        }
    }
});
" | Add-Content $outputfile
}


                    write-output "</script>`n</body>`n</html>" | Add-Content $outputfile

                }
                return $true
            }
            if($TargetMetric -eq "PSMUtilizationForXDays"){
                if([String]::IsNullOrEmpty($DayRange)){
                    Write-VPASOutput -str "NO DayRange SUPPLIED, ENTER DayRange (1 - 365): " -type Y
                    $DayRange = Read-Host
                }
                
                try{
                    $AmtDaysInt = [Int]$DayRange
                    if($AmtDaysInt -lt 1 -or $AmtDaysInt -gt 365){
                        Write-Verbose "INVALID INPUT FOR DAY RANGE: $DayRange ...MUST BE AN INTEGRET BETWEEN 1 - 365"
                        Write-VPASOutput -str "INVALID INPUT FOR DAY RANGE: $DayRange ...MUST BE AN INTEGRET BETWEEN 1 - 365" -type E
                        return $false
                    }
                }catch{
                    Write-Verbose "INVALID INPUT FOR DAY RANGE: $DayRange ...MUST BE AN INTEGER BETWEEN 1 - 365"
                    Write-VPASOutput -str "INVALID INPUT FOR DAY RANGE: $DayRange ...MUST BE AN INTEGER BETWEEN 1 - 365" -type E
                    Write-VPASOutput -str $_ -type E
                    return $false
                }

                #INITIALIZE HASH
                $RecordingsHash = @{}
                $MaxTime = ([int][double]::Parse((Get-Date (get-date (get-date).Date).ToLocalTime() -UFormat %s))) + 86400
                $MinTime = ($AmtDaysInt * 86400)
                $AllPSMs = Get-VPASSystemHealth -Component PSM

                foreach($rec in $AllPSMs.ComponentsDetails){
                    $ComponentUsername = $rec.ComponentUserName
                    
                    if($ComponentUsername -match "PSMApp_"){
                        $UniqueKey = $ComponentUsername
                        $RecordingsHash += @{
                            $UniqueKey = @{
                                Count = 0
                                RawData = @()
                            }
                        }
                    }
                }

                #GET RECORDINGS
                $AllRecordings = Get-VPASPSMSessions -SearchQuery " "
                if(!$AllRecordings){
                    Write-Verbose "FAILED TO RETRIEVE PSM SESSIONS"
                    Write-VPASOutput -str "FAILED TO RETRIEVE PSM SESSIONS" -type E
                    Write-VPASOutput -str $_ -type E
                    return $false
                }

                foreach($rec in $AllRecordings.Recordings){
                    $EpochStart = $rec.Start
                    $TargetPSM = $rec.RawProperties.ProviderID

                    if($EpochStart -le $MaxTime -and $EpochStart -ge $MinTime){
                        if($RecordingsHash.$TargetPSM){
                            $curCount = $RecordingsHash.$TargetPSM.Count
                            $curCount += 1
                            $RecordingsHash.$TargetPSM.Count = $curCount
                            $RecordingsHash.$TargetPSM.RawData += $rec
                        }
                    }
                }

                if($MetricFormat -eq "JSON" -or $MetricFormat -eq "ALL"){
                    $outputfile = "$OutputDirectory/PSMUtilizationFor" + $AmtDaysInt + "Days.json"
                    $OutputDataJSON = $RecordingsHash | ConvertTo-Json
                    Write-Output $OutputDataJSON | Set-Content $outputfile
                    return $OutputDataJSON
                }

                if($MetricFormat -eq "HTML" -or $MetricFormat -eq "ALL"){
                    $outputfile = "$OutputDirectory/PSMUtilizationFor" + $AmtDaysInt + "Days.html"
write-output "
<!DOCTYPE html>
<html>
<script src=`"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js`"></script>
<body>
" | Set-content $outputfile
                    
                    if($HTMLChart -eq "BarGraph" -or $HTMLChart -eq "ALL"){
                        write-output "<canvas id=`"myChartBAR`" style=`"width:100%;`"></canvas>`n<br><br><br>`n" | Add-Content $outputfile
                    }
                    if($HTMLChart -eq "LineGraph" -or $HTMLChart -eq "ALL"){
                        write-output "<canvas id=`"myChartLINE`" style=`"width:100%;`"></canvas>`n<br><br><br>`n"| Add-Content $outputfile
                    }
                    if($HTMLChart -eq "PieChart" -or $HTMLChart -eq "ALL"){
                        write-output "<canvas id=`"myChartPIE`" style=`"width:100%;`"></canvas>`n<br><br><br>`n"| Add-Content $outputfile
                    }
                    write-output "<script>" | Add-Content $outputfile

                    $tempstr = ""
                    $tempstr2 = ""
                    $tempstr3 = ""
                    $tempstr4 = ""
                    $AllKeys = $RecordingsHash.Keys
                    $GetMinMax = @()

                    foreach($key in $AllKeys){
                        $curCount = $RecordingsHash.$key.count
                        $GetMinMax += $curCount
                        $textColor =  '#{0:X6}' -f (Get-Random -Maximum 0x1000000)

                        $tempstr += "`"$key`","
                        $tempstr2 += "$curCount,"
                        $tempstr3 += "`"green`","
                        $tempstr4 += "`"$textColor`","
                    }

                    $GetMinMax = $GetMinMax | Sort-Object
                    $mintick = $GetMinMax[0]
                    $maxtick = $GetMinMax[$GetMinMax.Count - 1]

                    $tempstr = $tempstr.Substring(0,$tempstr.Length-1)
                    $tempstr2 = $tempstr2.Substring(0,$tempstr2.Length-1)
                    $tempstr3 = $tempstr3.Substring(0,$tempstr3.Length-1)
                    $tempstr4 = $tempstr4.Substring(0,$tempstr4.Length-1)
                    
                    if($HTMLChart -eq "BarGraph" -or $HTMLChart -eq "ALL"){
                        write-output "const xValuesBAR = [$tempstr];" | Add-Content $outputfile
                        write-output "const yValuesBAR = [$tempstr2];" | Add-Content $outputfile
                        write-output "const barColorsBAR = [$tempstr3];" | Add-Content $outputfile
                    }
                    if($HTMLChart -eq "LineGraph" -or $HTMLChart -eq "ALL"){
                        write-output "const xValuesLINE = [$tempstr];" | Add-Content $outputfile
                        write-output "const yValuesLINE = [$tempstr2];" | Add-Content $outputfile
                    }
                    if($HTMLChart -eq "PieChart" -or $HTMLChart -eq "ALL"){
                        write-output "const xValuesPIE = [$tempstr];" | Add-Content $outputfile
                        write-output "const yValuesPIE = [$tempstr2];" | Add-Content $outputfile
                        write-output "const barColorsPIE = [$tempstr4];" | Add-Content $outputfile
                    }

if($HTMLChart -eq "BarGraph" -or $HTMLChart -eq "ALL"){
#BAR
Write-Output "
new Chart(`"myChartBAR`", {
    type: `"bar`",
    data: {
        labels: xValuesBAR,
        datasets: [{
            backgroundColor: barColorsBAR,
            data: yValuesBAR
        }]
    },
    options: {
        legend: {display: false},
        title: {
            display: true,
            text: `"PSM Utilization For The Last $AmtDaysInt Days`"
        }
    }
});
" | Add-Content $outputfile
}
if($HTMLChart -eq "LineGraph" -or $HTMLChart -eq "ALL"){
#LINE
Write-Output "
new Chart(`"myChartLINE`", {
    type: `"line`",
    data: {
        labels: xValuesLINE,
        datasets: [{
            label: `"PSM Utilization For The Last $AmtDaysInt Days`",
            fill: false,
            lineTension: 0,
            backgroundColor: `"rgba(0,0,255,1.0)`",
            borderColor: `"rgba(0,0,255,0.1)`",
            data: yValuesLINE
        }]
    },
    options: {
        legend: {display: true},
        scales: {
            yAxes: [{ticks: {min: $mintick, max:$maxtick}}],
        }
    }
});
" | Add-Content $outputfile
}
if($HTMLChart -eq "PieChart" -or $HTMLChart -eq "ALL"){
#PIE
write-output "
new Chart(`"myChartPIE`", {
    type: `"pie`",
    data: {
        labels: xValuesPIE,
        datasets: [{
            backgroundColor: barColorsPIE,
            data: yValuesPIE
        }]
    },
    options: {
        title: {
            display: true,
            text: `"PSM Utilization For The Last $AmtDaysInt Days`"
        }
    }
});
" | Add-Content $outputfile
}


                    write-output "</script>`n</body>`n</html>" | Add-Content $outputfile

                }
                return $true
            }
            
            return $false
        }catch{
            Write-Verbose "UNABLE TO RUN REPORT...RETURNING FALSE"
            Write-VPASOutput -str "UNABLE TO RUN REPORT...RETURNING FALSE" -type E
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
