<#
.Synopsis
   GET CONNECTOR MANAGEMENT CONNECTORS
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETRIEVE CONNECTORS FROM CONNECTOR MANAGEMENT VIA SEARCH QUERY
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER SearchQuery
   Search string to find target resource
.EXAMPLE
   $TargetConnectors = Get-VPASCMConnectors -SearchQuery {SEARCH QUERY VALUE}
.OUTPUTS
   If successful:
   {
        "value":  [
                      {
                          "connectorId":  "ManagementAgent_jhgsad678235-asdf-erty-45656-9784yriefhjkasd",
                          "connectorStatus":  "Disconnected",
                          "platformType":  "OnPrem",
                          "connectorPoolId":  "jhgsad678235-asdf-erty-45656-9784yriefhjkasd",
                          "version":  "1.0.483.0",
                          "upgradeVersions":  "v1.0.581",
                          "installedAt":  1710823582160,
                          "updatedAt":  1718169798605,
                          "host":  "@{hostname=VmanCon01; privateIp=192.168.111.111; publicIp=22.222.22.222; os=windows; osVersion=10.0.20348; osName=Windows Server 2022 Standard; cloudRegion=; cloudAccount=; cpuType=12th Gen Intel(R) Core(TM) i7-1265U; totalCpu=1; usedCpu=-1.0; totalMemory=4.288097381591797; usedMemory=-1.0; hostConfig=}",
                          "components":  "  "
                      },
                      {
                          "connectorId":  "ManagementAgent_489723kjwdsbk-3456-7899-sdfg-kjsdnfb4389",
                          "connectorStatus":  "Active",
                          "platformType":  "OnPrem",
                          "connectorPoolId":  "489723kjwdsbk-3456-7899-sdfg-kjsdnfb4389",
                          "version":  "1.0.483.0",
                          "upgradeVersions":  "v1.0.581",
                          "installedAt":  1710820946924,
                          "updatedAt":  1723831555919,
                          "host":  "@{hostname=VmanCon02; privateIp=192.168.222.222; publicIp=333.3.333.33; os=windows; osVersion=10.0.20348; osName=Windows Server 2022 Standard Evaluation; cloudRegion=; cloudAccount=; cpuType=12th Gen Intel(R) Core(TM) i7-1265U; totalCpu=1; usedCpu=53.1; totalMemory=3.999034881591797; usedMemory=39.0; hostConfig=}",
                          "components":  "   "
                      }
                  ]
   }
   ---
   $false if failed
#>
function Get-VPASCMConnectors{
    [OutputType('System.Collections.Hashtable',[bool])]
    [CmdletBinding()]
    Param(

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter searchquery to find target connectors",Position=0)]
        [String]$SearchQuery,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED SUBDOMAIN VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            if($SubDomain -eq "N/A"){
                Write-VPASOutput -str "SelfHosted + PriviledgeCloud Standard solutions do not support this API Call, returning false" -type E
                $log = Write-VPASTextRecorder -inputval "SelfHosted + PrivilegeCloud Standard solutions do not support this API Call, returning false" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval $false -token $token -LogType RETURN
                return $false
            }

            write-verbose "MAKING API CALL TO CYBERARK"
            $uri = "https://$SubDomain.connectormanagement.cyberark.cloud/api/connectors"
            Write-Verbose "CONSTRUCTING URI: $uri"

            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $log = Write-VPASTextRecorder -inputval $response -token $token -LogType RETURNARRAY

            $output = @()
            foreach($rec in $response.connectors){
                $recConnectorID = $rec.connectorId
                $recHostname = $rec.host.hostname
                $recPublicIP = $rec.host.publicIP
                $recPrivateIP = $rec.host.privateIp

                if($recHostname -match $SearchQuery -or $recPublicIP -match $SearchQuery -or $recPrivateIP -match $SearchQuery){
                    $output += $rec
                }
            }

            $outputlog = @{
                value = $output
            } | ConvertTo-Json | ConvertFrom-Json
            $outputreturn = @{
                value = $output
            }
            $log = Write-VPASTextRecorder -inputval $outputlog -token $token -LogType RETURNARRAY
            Write-Verbose "RETURNING CONNECTOR DETAILS"
            return $outputreturn
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE CONNECTOR MANAGEMENT CONNECTORS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
