<#
.Synopsis
   GET ALL ROTATIONAL PLATFORMS
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET ALL ROTATIONAL PLATFORMS
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.EXAMPLE
   $AllRotationalPlatformsJSON = Get-VPASAllRotationalPlatforms
.OUTPUTS
   If successful:
   {
        "Platforms":  [
                          ...
                          {
                              "general":  "@{id=NewPlatform01; name=NewPlatform01; systemType=Windows; active=True; description=New platform for documentation 01; platformBaseID=WinDomain; platformType=regular}",
                              "properties":  "@{required=System.Object[]; optional=System.Object[]}",
                              "linkedAccounts":  " ",
                              "credentialsManagement":  "@{allowedSafes=.*; allowManualChange=True; performPeriodicChange=False; requirePasswordChangeEveryXDays=90; allowManualVerification=True; performPeriodicVerification=False; requirePasswordVerificationEveryXDays=7; allowManualReconciliation=True; automaticReconcileWhenUnsynched=False}",
                              "sessionManagement":  "@{requirePrivilegedSessionMonitoringAndIsolation=True; recordAndSaveSessionActivity=True; PSMServerID=PSMServer_hjkasd6789}",
                              "privilegedAccessWorkflows":  "@{requireDualControlPasswordAccessApproval=False; enforceCheckinCheckoutExclusiveAccess=False; enforceOnetimePasswordAccess=False}"
                          },
                          {
                              "general":  "@{id=NewPlatform02; name=NewPlatform02; systemType=Windows; active=True; description=New platform for documentation 02; platformBaseID=WinDomain; platformType=regular}",
                              "properties":  "@{required=System.Object[]; optional=System.Object[]}",
                              "linkedAccounts":  " ",
                              "credentialsManagement":  "@{allowedSafes=.*; allowManualChange=True; performPeriodicChange=False; requirePasswordChangeEveryXDays=90; allowManualVerification=True; performPeriodicVerification=False; requirePasswordVerificationEveryXDays=7; allowManualReconciliation=True; automaticReconcileWhenUnsynched=False}",
                              "sessionManagement":  "@{requirePrivilegedSessionMonitoringAndIsolation=True; recordAndSaveSessionActivity=True; PSMServerID=PSMServer_hjkasd6789}",
                              "privilegedAccessWorkflows":  "@{requireDualControlPasswordAccessApproval=False; enforceCheckinCheckoutExclusiveAccess=False; enforceOnetimePasswordAccess=False}"
                          },
                          ...
                      ],
        "Total":  67
   }
   ---
   $false if failed
#>
function Get-VPASAllRotationalPlatforms{
    [OutputType('System.Object')]
    [CmdletBinding()]
    Param(

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=0)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/passwordvault/api/platforms/rotationalGroups/"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/passwordvault/api/platforms/rotationalGroups/"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD
            write-verbose "MAKING API CALL"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }

            $log = Write-VPASTextRecorder -inputval $response -token $token -LogType RETURN
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO QUERY CYBERARK"
            Write-VPASOutput -str $_ -type E
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}