<#
.Synopsis
   GET DIRCECTORY MAPPINGS
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET DIRECTORY MAPPINGS
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER DomainName
   Target domain to query details for
.EXAMPLE
   $DirectoryMappingsJSON = Get-VPASDirectoryMappings -DomainName {DOMAIN NAME VALUE}
.OUTPUTS
   If successful:
   [
        {
            "LDAPBranch":  "DC=vman,DC=com",
            "MappingAuthorizations":  [
                                          "AddUpdateUsers",
                                          "AddSafes",
                                          "AddNetworkAreas",
                                          "ManageServerFileCategories",
                                          "AuditUsers",
                                          "ResetUsersPasswords",
                                          "ActivateUsers"
                                      ],
            "Location":  "\\",
            "AuthenticationMethod":  [
                                         "AuthTypeLDAP"
                                     ],
            "UserType":  "EPVUser",
            "DisableUser":  false,
            "UserActivityLogPeriod":  7,
            "UserExpiration":  0,
            "LogonFromHour":  0,
            "LogonToHour":  24,
            "UsedQuota":  -1,
            "AuthorizedInterfaces":  [

                                     ],
            "EnableENEWhenDisconnected":  false,
            "MappingID":  36,
            "DirectoryMappingOrder":  1000,
            "MappingName":  "Vault admins__vman.com",
            "LDAPQuery":  "",
            "DomainGroups":  [
                                 "CAVaultAdmins"
                             ]
        },
        {
            "LDAPBranch":  "DC=vman,DC=com",
            "MappingAuthorizations":  [
                                          "AuditUsers"
                                      ],
            "Location":  "\\",
            "AuthenticationMethod":  [
                                         "AuthTypeLDAP"
                                     ],
            "UserType":  "EPVUser",
            "DisableUser":  false,
            "UserActivityLogPeriod":  7,
            "UserExpiration":  0,
            "LogonFromHour":  0,
            "LogonToHour":  24,
            "UsedQuota":  -1,
            "AuthorizedInterfaces":  [

                                     ],
            "EnableENEWhenDisconnected":  false,
            "MappingID":  38,
            "DirectoryMappingOrder":  2000,
            "MappingName":  "Auditors__vman.com",
            "LDAPQuery":  "",
            "DomainGroups":  [
                                 "CAVaultAuditors"
                             ]
        },
        {
            "LDAPBranch":  "DC=vman,DC=com",
            "MappingAuthorizations":  [

                                      ],
            "Location":  "\\",
            "AuthenticationMethod":  [
                                         "AuthTypeLDAP"
                                     ],
            "UserType":  "EPVUser",
            "DisableUser":  false,
            "UserActivityLogPeriod":  7,
            "UserExpiration":  0,
            "LogonFromHour":  0,
            "LogonToHour":  24,
            "UsedQuota":  -1,
            "AuthorizedInterfaces":  [

                                     ],
            "EnableENEWhenDisconnected":  false,
            "MappingID":  40,
            "DirectoryMappingOrder":  3000,
            "MappingName":  "Users__vman.com",
            "LDAPQuery":  "",
            "DomainGroups":  [
                                 "CAVaultUsers"
                             ]
        }
   ]
   ---
   $false if failed
#>
function Get-VPASDirectoryMappings{
    [OutputType('System.Object',[bool])]
    [CmdletBinding()]
    Param(

        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true,HelpMessage="Enter target Domain to query DirectoryMappings (for example: vman.com)",Position=0)]
        [String]$DomainName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED PVWA VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"
        Write-Verbose "SUCCESSFULLY PARSED DOMAIN NAME: $DomainName"

        try{

            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/PasswordVault/API/Configuration/LDAP/Directories/$DomainName/Mappings"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/PasswordVault/API/Configuration/LDAP/Directories/$DomainName/Mappings"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD
            Write-Verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $outputlog = $response | ConvertTo-Json | ConvertFrom-Json
            $log = Write-VPASTextRecorder -inputval $outputlog -token $token -LogType RETURNARRAY
            Write-Verbose "SUCCESSFULLY RETRIEVED DIRECTORY MAPPINGS FOR DOMAIN NAME: $DomainName"
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO QUERY DIRECTORY MAPPINGS FOR DOMAIN NAME: $DomainName"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
