<#
.Synopsis
   GET CONNECTOR MANAGEMENT CONNECTOR POOL DETAILS
   CREATED BY: Vadim Melamed, EMAIL: vmelamed5@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETRIEVE CONNECTOR POOL DETAILS FROM CONNECTOR MANAGEMENT
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER PoolID
   UniqueID of the target connector pool in ConnectorManagement
.PARAMETER PoolName
   Unique name of the target connector pool in ConnectorManagement
.EXAMPLE
   $ConnectorPoolDetails = Get-VPASCMConnectorPoolDetails -PoolID {POOL ID VALUE}
.EXAMPLE
   $ConnectorPoolDetails = Get-VPASCMConnectorPoolDetails -PoolName {POOL NAME VALUE}
.OUTPUTS
   If successful:
   {
        "poolId":  "ahdkj9823-asdf-ghjk-1234-9487fhskdj",
        "name":  "Test",
        "description":  null
   }
   ---
   $false if failed
#>
function Get-VPASCMConnectorPoolDetails{
    [OutputType('System.Collections.Hashtable',[bool])]
    [CmdletBinding()]
    Param(

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=0)]
        [String]$PoolID,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=1)]
        [String]$PoolName,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true,Position=2)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        Write-Verbose "SUCCESSFULLY PARSED SUBDOMAIN VALUE"
        Write-Verbose "SUCCESSFULLY PARSED TOKEN VALUE"

        try{
            if($SubDomain -eq "N/A"){
                Write-VPASOutput -str "SelfHosted + PriviledgeCloud Standard solutions do not support this API Call, returning false" -type E
                $log = Write-VPASTextRecorder -inputval "SelfHosted + PrivilegeCloud Standard solutions do not support this API Call, returning false" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval $false -token $token -LogType RETURN
                return $false
            }

            if([String]::IsNullOrEmpty($PoolID)){
                Write-Verbose "NO CONNECTOR POOL ID PROVIDED...INVOKING HELPER FUNCTION TO RETRIEVE UNIQUE CONNECTOR POOL ID BASED ON SPECIFIED PARAMETERS"
                $PoolID = Get-VPASCMConnectorPoolIDHelper -token $token -SearchQuery $PoolName
                Write-Verbose "RETURNING CONNECTOR POOL ID"
            }
            else{
                Write-Verbose "CONNECTOR POOL ID SUPPLIED, SKIPPING HELPER FUNCTION"
            }

            if($PoolID -eq -1){
                $log = Write-VPASTextRecorder -inputval "COULD NOT FIND TARGET CONNECTOR POOL ID: $PoolID" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
                Write-Verbose "COULD NOT FIND TARGET CONNECTOR POOL ID: $PoolID"
                Write-VPASOutput -str "COULD NOT FIND TARGET CONNECTOR POOL ID: $PoolID" -type E
                return $false
            }
            else{
                write-verbose "MAKING API CALL TO CYBERARK"
                $uri = "https://$SubDomain.connectormanagement.cyberark.cloud/api/connector-pools/$PoolID"
                Write-Verbose "CONSTRUCTING URI: $uri"

                $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
                $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

                if($sessionval){
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
                }
                else{
                    $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
                }
                $log = Write-VPASTextRecorder -inputval $response -token $token -LogType RETURNARRAY
                Write-Verbose "RETURNING CONNECTOR POOL DETAILS"
                return $response
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE CONNECTOR MANAGEMENT CONNECTOR POOL DETAILS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
