<#
.Synopsis
   GET ALL CONNECTOR MANAGEMENT COMPONENTS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETRIEVE ALL COMPONENTS FROM CONNECTOR MANAGEMENT
.LINK
   https://vpasmodule.com/commands/Get-VPASCMAllComponents
.NOTES
   SelfHosted: FALSE
   PrivCloudStandard: FALSE
   SharedServices: TRUE
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.PARAMETER ExportToCSV
   Output results to a CSV file found in AppData\Local\VPASModuleOutputs directory
.PARAMETER CSVDirectory
   Output directory where the exported CSV file will be saved to
   Default value: C:\Users\{CurrentUser}\AppData\Local\VPASModuleOutputs\ExportedCSVs
.EXAMPLE
   $AllComponents = Get-VPASCMAllComponents
.EXAMPLE
   $InputParameters = @{
        ExportToCSV = $true|$false
        CSVDirectory = "C:\Temp"
   }
   $AllComponents = Get-VPASCMAllComponents -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "components":  [
                           {
                               "componentId":  "189237bdhj-akjhsd-43b0-ac11-ahsgd871010101",
                               "componentName":  "Central Policy Manager Scanner",
                               "acronym":  "cpm scanner",
                               "componentStatus":  "Active",
                               "connectorId":  "ManagementAgent_ecbf2ce1-kjhd-2345-ag48-jjdgsfsret5698",
                               "version":  "13.2.0.2",
                               "upgradeVersions":  "",
                               "usedCpu":  0.439,
                               "usedMemory":  1.531,
                               "installedAt":  1710821628343,
                               "updatedAt":  1723831555919,
                               "maintenanceStatus":  null
                           },
                           {
                               "componentId":  "189237bdhj-akjhsd-43b0-ac11-ahsgd87hg687131",
                               "componentName":  "Privileged Session Manager",
                               "acronym":  "psm",
                               "componentStatus":  "Active",
                               "connectorId":  "ManagementAgent_ecbf2ce1-kjhd-2345-ag48-jjdgsfsret5698",
                               "version":  "14.2.0.3",
                               "upgradeVersions":  "v14.3.0.8",
                               "usedCpu":  0.304,
                               "usedMemory":  0.949,
                               "installedAt":  1711987268166,
                               "updatedAt":  1723831555919,
                               "maintenanceStatus":  null
                           },
                           {
                               "componentId":  "ManagementAgent_ecbf2ce1-kjhd-2345-ag48-jjdgsfsret5698",
                               "componentName":  "Management Agent",
                               "acronym":  "Management Agent",
                               "componentStatus":  "Active",
                               "connectorId":  "ManagementAgent_ecbf2ce1-kjhd-2345-ag48-jjdgsfsret5698",
                               "version":  "1.0.483.0",
                               "upgradeVersions":  "v1.0.581",
                               "usedCpu":  2.91,
                               "usedMemory":  0.669,
                               "installedAt":  1710820946924,
                               "updatedAt":  1723831555919,
                               "maintenanceStatus":  null
                           },
                           {
                               "componentId":  "189237bdhj-akjhsd-43b0-ac11-ahsgd87ajhsgdhja",
                               "componentName":  "Password Manager",
                               "acronym":  "cpm",
                               "componentStatus":  "Active",
                               "connectorId":  "ManagementAgent_ecbf2ce1-kjhd-2345-ag48-jjdgsfsret5698",
                               "version":  "14.0.0.6",
                               "upgradeVersions":  "v14.2.1.6",
                               "usedCpu":  0.661,
                               "usedMemory":  0.917,
                               "installedAt":  1710821627249,
                               "updatedAt":  1723831555919,
                               "maintenanceStatus":  null
                           }
                       ]
   }
   ---
   $false if failed
#>
function Get-VPASCMAllComponents{
    [OutputType('System.Collections.Hashtable',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(
        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [Switch]$ExportToCSV,

        [Parameter(Mandatory=$false,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true)]
        [String]$CSVDirectory,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("ExportToCSV","CSVDirectory")
                        MandatoryKeys = @()
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE COMPONENTS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{
            if($SubDomain -eq "N/A"){
                Write-VPASOutput -str "SelfHosted + PriviledgeCloud Standard solutions do not support this API Call, returning false" -type E
                $log = Write-VPASTextRecorder -inputval "SelfHosted + PrivilegeCloud Standard solutions do not support this API Call, returning false" -token $token -LogType MISC
                $log = Write-VPASTextRecorder -inputval $false -token $token -LogType RETURN
                return $false
            }

            write-verbose "MAKING API CALL TO CYBERARK"
            $uri = "https://$SubDomain.connectormanagement.cyberark.cloud/api/components"
            Write-Verbose "CONSTRUCTING URI: $uri"

            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $log = Write-VPASTextRecorder -inputval $response -token $token -LogType RETURNARRAY
            if($ExportToCSV){
	            $runexport = Write-VPASExportCSV -Data $response -CommandName $CommandName -CSVDirectory $CSVDirectory
            }
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE CONNECTOR MANAGEMENT COMPONENTS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
