<#
.Synopsis
   ADD ALLOWED IP
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO ADD AN ALLOWED IP FOR PRIVILEGE CLOUD SHARED SERVICES
.LINK
   https://vpasmodule.com/commands/Add-VPASAllowedIP
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER AllowedValue
   Target value that will be whitelisted to allow cyberark cloud to communicate to
   CIDR ranges (/22 netmask or /32 netmask) can be utilized to add a range of IP addresses to the allowlist
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.EXAMPLE
   $AddAllowedIPJSON = Add-VPASAllowedIP -AllowedValue {ALLOWEDVALUE VALUE}
.EXAMPLE
   $InputParameters = @{
        AllowedValue = "99.99.99.99"
   }
   $AddAllowedIPJSON = Add-VPASAllowedIP -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "taskId":  "f9e4a8b3-b09e-40d2-9ece-e31b1234jhgb",
        "status":  "IN_PROGRESS",
        "params":  {
                       "createdAt":  "Fri Aug 16 03:27:42 GMT 2024",
                       "candidatePublicIPs":  [
                                                  "1.2.3.4/32",
                                                  "5.6.7.8/32"
                                              ]
                   }
   }
   ---
   $false if failed
#>
function Add-VPASAllowedIP{
    [OutputType([bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(

        [Parameter(Mandatory=$true,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true,HelpMessage="Enter new AllowedValue (for example: 55.55.55.55/32)")]
        [String]$AllowedValue,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("AllowedValue")
                        MandatoryKeys = @("AllowedValue")
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO ADD IP"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{
            Write-Verbose "RETRIEVING CURRENT ALLOWED VALUES"
            $CurrentValues = Get-VPASAllowedIPs
            $AllowedIPsArr = @()
            foreach($rec in $CurrentValues.customerPublicIPs){
                $AllowedIPsArr += $rec
                Write-Verbose "ADDING $rec TO ALLOWED VALUES"
            }
            $AllowedIPsArr += $AllowedValue
            Write-Verbose "ADDING $AllowedValue TO ALLOWED VALUES"

            write-verbose "INITIALIZING API PARAMETERS"
            $params = @{
                customerPublicIPs = $AllowedIPsArr
            }
            $log = Write-VPASTextRecorder -inputval $params -token $token -LogType PARAMS
            $params = $params | ConvertTo-Json

            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/api/advanced-settings/ip-allowlist"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/api/advanced-settings/ip-allowlist"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "PUT" -token $token -LogType METHOD

            write-verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method PUT -Body $params -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method PUT -Body $params -ContentType "application/json"
            }
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: TRUE" -token $token -LogType MISC
            Write-Verbose "SUCCESSFULLY ADDED ALLOWED VALUE: $AllowedValue"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO ADD ALLOWED VALUE: $AllowedValue"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
