<#
.Synopsis
   GET PLATFORM DETAILS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET DETAILS ABOUT A PLATFORM IN CYBERARK
.LINK
   https://vpasmodule.com/commands/Get-VPASPlatformDetails
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER platformID
   Unique PlatformID to retrieve details for
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.EXAMPLE
   $PlatformDetailsJSON = Get-VPASPlatformDetails -platformID {PLATFORMID VALUE}
.EXAMPLE
   $InputParameters = @{
        platformID = "TargetPlatformID"
   }
   $PlatformDetailsJSON = Get-VPASPlatformDetails -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "PlatformID":  "WinDomain",
        "Details":  {
                        "PolicyID":  "WinDomain",
                        "PolicyName":  "Windows Domain Account",
                        "SearchForUsages":  "Yes",
                        "PolicyType":  "regular",
                        "ImmediateInterval":  "5",
                        "Interval":  "1440",
                        "MaxConcurrentConnections":  "3",
                        "AllowedSafes":  ".*",
                        "MinValidityPeriod":  "60",
                        "ResetOveridesMinValidity":  "yes",
                        "ResetOveridesTimeFrame":  "yes",
                        "Timeout":  "30",
                        "UnlockIfFail":  "no",
                        "UnrecoverableErrors":  "2103,2105,2121",
                        "MaximumRetries":  "5",
                        "MinDelayBetweenRetries":  "90",
                        "DllName":  "PMWindows.dll",
                        "XMLFile":  "yes",
                        "AllowManualChange":  "Yes",
                        "PerformPeriodicChange":  "No",
                        "HeadStartInterval":  "5",
                        "FromHour":  "-1",
                        "ToHour":  "-1",
                        "ChangeNotificationPeriod":  "-1",
                        "DaysNotifyPriorExpiration":  "7",
                        "VFAllowManualVerification":  "Yes",
                        "VFPerformPeriodicVerification":  "No",
                        "VFFromHour":  "-1",
                        "VFToHour":  "-1",
                        "RCAllowManualReconciliation":  "Yes",
                        "RCAutomaticReconcileWhenUnsynched":  "No",
                        "RCReconcileReasons":  "2114,2115,2106,2101",
                        "RCFromHour":  "-1",
                        "RCToHour":  "-1",
                        "NFNotifyPriorExpiration":  "No",
                        "NFPriorExpirationRecipients":  "",
                        "NFNotifyOnPasswordDisable":  "Yes",
                        "NFOnPasswordDisableRecipients":  "",
                        "NFNotifyOnVerificationErrors":  "Yes",
                        "NFOnVerificationErrorsRecipients":  "",
                        "NFNotifyOnPasswordUsed":  "No",
                        "NFOnPasswordUsedRecipients":  "",
                        "PasswordLength":  "12",
                        "MinUpperCase":  "2",
                        "MinLowerCase":  "2",
                        "MinDigit":  "1",
                        "MinSpecial":  "1",
                        "OneTimePassword":  "No",
                        "ExpirationPeriod":  "90",
                        "VFVerificationPeriod":  "7",
                        "PasswordLevelRequestTimeframe":  "No"
                    },
        "Active":  true
   }
   ---
   $false if failed
#>
function Get-VPASPlatformDetails{
    [OutputType('System.Object',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(

        [Parameter(Mandatory=$true,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true,HelpMessage="Enter target PlatformID to query platform details (for example: WinServerLocal)")]
        [String]$platformID,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("platformID")
                        MandatoryKeys = @("platformID")
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE PLATFORM DETAILS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{

            Write-Verbose "MAKING API CALL TO CYBERARK"

            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/PasswordVault/API/Platforms/$platformID"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/PasswordVault/API/Platforms/$platformID"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $outputlog = $response.details
            $log = Write-VPASTextRecorder -inputval $outputlog -token $token -LogType RETURN
            Write-Verbose "PARSING DATA FROM CYBERARK"
            Write-Verbose "RETURNING PLATFORM DETAILS"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO RETRIEVE PLATFORM DETAILS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
