<#
.Synopsis
   GET ALL APPLICATIONS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO RETURN ALL APPLICATION IDS IN CYBERARK
.LINK
   https://vpasmodule.com/commands/Get-VPASAllApplications
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.EXAMPLE
   $ApplicationsJSON = Get-VPASAllApplications
.EXAMPLE
   $InputParameters = @{}
   $ApplicationsJSON = Get-VPASAllApplications -InputParameters $InputParameters
.OUTPUTS
   If successful:
   [
        {
            "value":  [
                          "VPasAppIDTest",
                          {
                              "AccessPermittedFrom":  0,
                              "AccessPermittedTo":  24,
                              "AllowExtendedAuthenticationRestrictions":  false,
                              "AppID":  "VPasAppIDTest",
                              "BusinessOwnerEmail":  "",
                              "BusinessOwnerFName":  "",
                              "BusinessOwnerLName":  "",
                              "BusinessOwnerPhone":  "",
                              "Description":  "",
                              "Disabled":  false,
                              "ExpirationDate":  null,
                              "Location":  "\\"
                          }
                      ]
        },
        {
            "value":  [
                          "VpasModuleAppIDTest",
                          {
                              "AccessPermittedFrom":  0,
                              "AccessPermittedTo":  24,
                              "AllowExtendedAuthenticationRestrictions":  false,
                              "AppID":  "VpasModuleAppIDTest",
                              "BusinessOwnerEmail":  "vadim.melamed@vman.com",
                              "BusinessOwnerFName":  "vadim",
                              "BusinessOwnerLName":  "melamed",
                              "BusinessOwnerPhone":  "",
                              "Description":  "Testing appID with text auditing",
                              "Disabled":  false,
                              "ExpirationDate":  null,
                              "Location":  "\\"
                          }
                      ]
        },
        {
            "value":  [
                          "AIMWebService",
                          {
                              "AccessPermittedFrom":  0,
                              "AccessPermittedTo":  24,
                              "AllowExtendedAuthenticationRestrictions":  false,
                              "AppID":  "AIMWebService",
                              "BusinessOwnerEmail":  "",
                              "BusinessOwnerFName":  "",
                              "BusinessOwnerLName":  "",
                              "BusinessOwnerPhone":  "",
                              "Description":  "",
                              "Disabled":  false,
                              "ExpirationDate":  null,
                              "Location":  "\\"
                          }
                      ]
        }
   ]
   ---
   $false if failed
#>
function Get-VPASAllApplications{
    [OutputType('System.Object',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(
        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @()
                        MandatoryKeys = @()
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE APPLICATIONS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{

            $outputreturn = @()
            write-verbose "MAKING API CALL TO CYBERARK"
            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/PasswordVault/WebServices/PIMServices.svc/Applications/"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/PasswordVault/WebServices/PIMServices.svc/Applications/"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }

            Write-Verbose "PARSING DATA FROM CYBERARK"
            $output = $response.application
            foreach($res in $output){
                $rec = @()
                $rec += $res.AppID
                $rec += $res
                $outputreturn = $outputreturn + ,$rec
            }

            $outputlog = $response
            $log = Write-VPASTextRecorder -inputval $outputlog -token $token -LogType RETURNARRAY

            Write-Verbose "RETURNING ARRAY OF APPLICATION IDS"
            return $outputreturn
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO RETRIEVE APPLICATION IDS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
