<#
.Synopsis
   GET ALL ACTIVE SESSIONS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET ALL ACTIVE PSM SESSIONS
.LINK
   https://vpasmodule.com/commands/Get-VPASAllActiveSessions
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.EXAMPLE
   $AllActiveSessionsJSON = Get-VPASAllActiveSessions
.EXAMPLE
   $InputParameters = @{}
   $AllActiveSessionsJSON = Get-VPASAllActiveSessions -InputParameters $InputParameters
.OUTPUTS
   If successful:
   {
        "LiveSessions":  [
                             {
                                 "CanTerminate":  false,
                                 "CanMonitor":  true,
                                 "CanSuspend":  false,
                                 "SessionID":  "31_24",
                                 "SessionGuid":  "737160df-bba6-494f-875d-8bcf0f5ef9db",
                                 "SafeName":  "PSMRecordings",
                                 "FolderName":  "Root",
                                 "IsLive":  true,
                                 "FileName":  "737160df-bba6-494f-875d-8bcf0f5ef9db.session",
                                 "Start":  1724215310,
                                 "End":  0,
                                 "Duration":  115,
                                 "User":  "administrator",
                                 "RemoteMachine":  "192.168.20.126",
                                 "ProtectionDate":  0,
                                 "ProtectedBy":  "",
                                 "ProtectionEnabled":  false,
                                 "AccountUsername":  "PSMTestUser",
                                 "AccountPlatformID":  "WinServerLocal",
                                 "AccountAddress":  "192.168.20.126",
                                 "PIMSuCommand":  "",
                                 "PIMSuCWD":  "",
                                 "ConnectionComponentID":  "PSM-RDP",
                                 "PSMRecordingEntity":  "SessionRecording",
                                 "TicketID":  "",
                                 "FromIP":  "192.168.20.1",
                                 "Protocol":  "RDP",
                                 "Client":  "RDP",
                                 "RiskScore":  -1,
                                 "Severity":  "",
                                 "IncidentDetails":  null,
                                 "RawProperties":  "@{Address=192.168.20.126; ConnectionComponentID=PSM-RDP; DeviceType=Operating System; EntityVersion=1.0; ExpectedRecordingsList=737160df-bba6-494f-875d-8bcf0f5ef9db.WIN.txt,737160df-bba6-494f-875d-8bcf0f5ef9db.VID.avi; PSMClientApp=mstsc.exe; PSMPasswordID=5; PSMProtocol=RDP; PSMRecordingEntity=SessionRecording; PSMRemoteMachine=192.168.20.126; PSMSafeID=28; PSMSourceAddress=192.168.20.1; PSMStartTime=1724215310; PSMStatus=Placeholder; PSMVaultUserName=administrator; PolicyID=WinServerLocal; ProviderID=PSMApp_COMPONENTS; UserName=PSMTestUser; Safe=PSMRecordings; Folder=Root; Name=737160df-bba6-494f-875d-8bcf0f5ef9db.session}",
                                 "RecordingFiles":  "",
                                 "RecordedActivities":  "",
                                 "VideoSize":  null,
                                 "TextSize":  null,
                                 "DetailsUrl":  "Livesessiondetails.aspx?Data=UFNNUmVjb3JkaW5nc15AXlJvb3ReQF43MzcxNjBkZi1iYmE2LTQ5NGYtODc1ZC04YmNmMGY1ZWY5ZGIuc2Vzc2lvbl5AXjBeQF5GYWxzZV5AXkZhbHNlXkBeXkBeQmFja1VSTD1Nc2dFcnI9TXNnSW5mbz0%3d"
                             }
                         ],
        "Total":  1
   }
   ---
   $false if failed
#>
function Get-VPASAllActiveSessions{
    [OutputType('System.Object',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(
        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @()
                        MandatoryKeys = @()
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE ACTIVE SESSIONS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{

            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/PasswordVault/api/LiveSessions"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/PasswordVault/api/LiveSessions"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD
            write-verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $outputlog = $response
            $log = Write-VPASTextRecorder -inputval $outputlog -token $token -LogType RETURNARRAY
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO GET ACTIVE SESSIONS"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
