<#
.Synopsis
   GET DIRCECTORY MAPPINGS
   CREATED BY: Vadim Melamed, EMAIL: vpasmodule@gmail.com
.DESCRIPTION
   USE THIS FUNCTION TO GET DIRECTORY MAPPINGS
.LINK
   https://vpasmodule.com/commands/Get-VPASDirectoryMappings
.PARAMETER token
   HashTable of data containing various pieces of login information (PVWA, LoginToken, HeaderType, etc).
   If -token is not passed, function will use last known hashtable generated by New-VPASToken
.PARAMETER DomainName
   Target domain to query details for
.PARAMETER InputParameters
   HashTable of values containing the parameters required to make the API call
.EXAMPLE
   $DirectoryMappingsJSON = Get-VPASDirectoryMappings -DomainName {DOMAIN NAME VALUE}
.EXAMPLE
   $InputParameters = @{
        DomainName = "vman.com"
   }
   $DirectoryMappingsJSON = Get-VPASDirectoryMappings -InputParameters $InputParameters
.OUTPUTS
   If successful:
   [
        {
            "LDAPBranch":  "DC=vman,DC=com",
            "MappingAuthorizations":  [
                                          "AddUpdateUsers",
                                          "AddSafes",
                                          "AddNetworkAreas",
                                          "ManageServerFileCategories",
                                          "AuditUsers",
                                          "ResetUsersPasswords",
                                          "ActivateUsers"
                                      ],
            "Location":  "\\",
            "AuthenticationMethod":  [
                                         "AuthTypeLDAP"
                                     ],
            "UserType":  "EPVUser",
            "DisableUser":  false,
            "UserActivityLogPeriod":  7,
            "UserExpiration":  0,
            "LogonFromHour":  0,
            "LogonToHour":  24,
            "UsedQuota":  -1,
            "AuthorizedInterfaces":  [

                                     ],
            "EnableENEWhenDisconnected":  false,
            "MappingID":  36,
            "DirectoryMappingOrder":  1000,
            "MappingName":  "Vault admins__vman.com",
            "LDAPQuery":  "",
            "DomainGroups":  [
                                 "CAVaultAdmins"
                             ]
        },
        {
            "LDAPBranch":  "DC=vman,DC=com",
            "MappingAuthorizations":  [
                                          "AuditUsers"
                                      ],
            "Location":  "\\",
            "AuthenticationMethod":  [
                                         "AuthTypeLDAP"
                                     ],
            "UserType":  "EPVUser",
            "DisableUser":  false,
            "UserActivityLogPeriod":  7,
            "UserExpiration":  0,
            "LogonFromHour":  0,
            "LogonToHour":  24,
            "UsedQuota":  -1,
            "AuthorizedInterfaces":  [

                                     ],
            "EnableENEWhenDisconnected":  false,
            "MappingID":  38,
            "DirectoryMappingOrder":  2000,
            "MappingName":  "Auditors__vman.com",
            "LDAPQuery":  "",
            "DomainGroups":  [
                                 "CAVaultAuditors"
                             ]
        },
        {
            "LDAPBranch":  "DC=vman,DC=com",
            "MappingAuthorizations":  [

                                      ],
            "Location":  "\\",
            "AuthenticationMethod":  [
                                         "AuthTypeLDAP"
                                     ],
            "UserType":  "EPVUser",
            "DisableUser":  false,
            "UserActivityLogPeriod":  7,
            "UserExpiration":  0,
            "LogonFromHour":  0,
            "LogonToHour":  24,
            "UsedQuota":  -1,
            "AuthorizedInterfaces":  [

                                     ],
            "EnableENEWhenDisconnected":  false,
            "MappingID":  40,
            "DirectoryMappingOrder":  3000,
            "MappingName":  "Users__vman.com",
            "LDAPQuery":  "",
            "DomainGroups":  [
                                 "CAVaultUsers"
                             ]
        }
   ]
   ---
   $false if failed
#>
function Get-VPASDirectoryMappings{
    [OutputType('System.Object',[bool])]
    [CmdletBinding(DefaultParameterSetName='Set1')]
    Param(

        [Parameter(Mandatory=$true,ParameterSetName='Set1',ValueFromPipelineByPropertyName=$true,HelpMessage="Enter target Domain to query DirectoryMappings (for example: vman.com)")]
        [String]$DomainName,

        [Parameter(Mandatory=$true,ParameterSetName='InputParameters',ValueFromPipelineByPropertyName=$true,HelpMessage="Hashtable of parameters required to make API call, refer to get-help -examples for valid inputs")]
        [hashtable]$InputParameters,

        [Parameter(Mandatory=$false,ValueFromPipelineByPropertyName=$true)]
        [hashtable]$token
    )

    Begin{
        $tokenval,$sessionval,$PVWA,$Header,$ISPSS,$IdentityURL,$EnableTextRecorder,$AuditTimeStamp,$NoSSL,$VaultVersion,$HideWarnings,$AuthenticatedAs,$SubDomain,$EnableTroubleshooting = Get-VPASSession -token $token
        $CommandName = $MyInvocation.MyCommand.Name
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType COMMAND
    }
    Process{
        try{
            if($PSCmdlet.ParameterSetName -eq "InputParameters"){
                $KeyHash = @{
                    set1 = @{
                        AcceptableKeys = @("DomainName")
                        MandatoryKeys = @("DomainName")
                    }
                }
                $CheckSet = Test-VPASHashtableKeysHelper -InputHash $InputParameters -KeyHash $KeyHash

                if(!$CheckSet){
                    $log = Write-VPASTextRecorder -inputval "FAILED TO FIND TARGET PARAMETER SET" -token $token -LogType MISC
                    Write-Verbose "FAILED TO FIND TARGET PARAMETER SET"
                    Write-VPASOutput -str "FAILED TO FIND TARGET PARAMETER SET...VIEW EXAMPLES BELOW:" -type E
                    $examples = Write-VPASExampleHelper -CommandName $CommandName
                    return $false
                }
                else{
                    foreach($key in $InputParameters.Keys){
                        Set-Variable -Name $key -Value $InputParameters.$key
                    }
                }
            }
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "FAILED TO RETRIEVE DIRECTORY MAPPINGS"
            Write-VPASOutput -str $_ -type E
            return $false
        }

        try{

            if($NoSSL){
                Write-Verbose "NO SSL ENABLED, USING HTTP INSTEAD OF HTTPS"
                $uri = "http://$PVWA/PasswordVault/API/Configuration/LDAP/Directories/$DomainName/Mappings"
            }
            else{
                Write-Verbose "SSL ENABLED BY DEFAULT, USING HTTPS"
                $uri = "https://$PVWA/PasswordVault/API/Configuration/LDAP/Directories/$DomainName/Mappings"
            }
            $log = Write-VPASTextRecorder -inputval $uri -token $token -LogType URI
            $log = Write-VPASTextRecorder -inputval "GET" -token $token -LogType METHOD
            Write-Verbose "MAKING API CALL TO CYBERARK"

            if($sessionval){
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json" -WebSession $sessionval
            }
            else{
                $response = Invoke-RestMethod -Headers @{"Authorization"=$Header} -Uri $uri -Method GET -ContentType "application/json"
            }
            $outputlog = $response | ConvertTo-Json | ConvertFrom-Json
            $log = Write-VPASTextRecorder -inputval $outputlog -token $token -LogType RETURNARRAY
            Write-Verbose "SUCCESSFULLY RETRIEVED DIRECTORY MAPPINGS FOR DOMAIN NAME: $DomainName"
            Write-Verbose "RETURNING JSON OBJECT"
            return $response
        }catch{
            $log = Write-VPASTextRecorder -inputval $_ -token $token -LogType ERROR
            $log = Write-VPASTextRecorder -inputval "REST API COMMAND RETURNED: FALSE" -token $token -LogType MISC
            Write-Verbose "UNABLE TO QUERY DIRECTORY MAPPINGS FOR DOMAIN NAME: $DomainName"
            Write-VPASOutput -str $_ -type E
            return $false
        }
    }
    End{
        $log = Write-VPASTextRecorder -inputval $CommandName -token $token -LogType DIVIDER
    }
}
